Repository woowacourse-teams/2023-votogether, pull requests merged in 2023-10, with the labels that each got.

#701 lightHouse 웹 접근성 93점을 98점으로 올렸음
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/style.ts
  frontend/src/components/post/Post/index.tsx
  frontend/src/components/post/Post/style.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostList/style.ts
Labels: FE, 🐾 개발

#698 선택지에서 이미지 붙혀넣기로 업로드 가능하도록 구현
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/WritingVoteOption.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/index.tsx
  frontend/src/hooks/useWritingOption.tsx
Labels: FE, 🐾 개발

#699 댓글 더 보기시 보이지 않는 인풋에 포커스되어 네모 박스가 보이는 문제 수정
  frontend/src/components/comment/CommentList/style.ts
Labels: FE, 🐛 버그

#689 테스트 컨테이너를 이용한 리프레시 토큰 검증 추가
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/test/java/com/votogether/domain/auth/service/AuthServiceTest.java
Labels: BE, 👷🏻 테스트

#481 요청, 응답 로그 설정
  backend/build.gradle
  backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/votogether/global/log/aop/ConnectionMethodInterceptor.java
  backend/src/main/java/com/votogether/global/log/aop/LogAop.java
  backend/src/main/java/com/votogether/global/log/aop/Logger.java
  backend/src/main/java/com/votogether/global/log/aop/PreparedStatementMethodInterceptor.java
  backend/src/main/java/com/votogether/global/log/aop/QueryCountAop.java
  backend/src/main/java/com/votogether/global/log/context/AnonymousLogId.java
  backend/src/main/java/com/votogether/global/log/context/AuthenticatedLogId.java
  backend/src/main/java/com/votogether/global/log/context/LogContext.java
  backend/src/main/java/com/votogether/global/log/context/LogId.java
  backend/src/main/java/com/votogether/global/log/context/MemberIdHolder.java
  backend/src/main/java/com/votogether/global/log/context/QueryCount.java
  backend/src/main/java/com/votogether/global/log/log4j2/Attachment.java
  backend/src/main/java/com/votogether/global/log/log4j2/SlackAppender.java
  backend/src/main/java/com/votogether/global/log/log4j2/SlackMessage.java
  backend/src/main/java/com/votogether/global/log/presentation/MessageBodyReader.java
  backend/src/main/java/com/votogether/global/log/presentation/RepeatReadableRequestWrapper.java
  backend/src/main/java/com/votogether/global/log/presentation/RequestLog.java
  backend/src/main/java/com/votogether/global/log/presentation/RequestLogInterceptor.java
  backend/src/main/java/com/votogether/global/log/presentation/RequestResponseCacheFilter.java
  backend/src/main/java/com/votogether/global/log/presentation/ResponseLog.java
  backend/src/main/java/com/votogether/global/util/CorsUtils.java
  backend/src/main/java/com/votogether/global/util/MultipartUtils.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/log4j2-dev.xml
  backend/src/main/resources/log4j2-local.xml
  backend/src/main/resources/log4j2-prod.xml
  backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/votogether/domain/auth/service/AuthServiceTest.java
  backend/src/test/java/com/votogether/domain/category/contorller/CategoryControllerTest.java
  backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/category/service/CategoryServiceTest.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostQueryControllerTest.java
  backend/src/test/java/com/votogether/domain/ranking/controller/RankingControllerTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportNicknameStrategyTest.java
  backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
  backend/src/test/java/com/votogether/test/ControllerTest.java
  backend/src/test/java/com/votogether/test/ServiceTest.java
  backend/src/test/java/com/votogether/test/annotation/RepositoryTest.java
  backend/src/test/java/com/votogether/test/annotation/ServiceTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🐳 인프라, ✅ 우선 순위 보통

#717 [BUG] CORS 에러 해결
  backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
Labels: BE, 🐛 버그

#728 [TEMP] CORS url 추가
  backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
Labels: BE

#706 게시글 작성 시 본문 링크 삽입을 하지 않더라도 사용자에게 링크 클릭이 가능하도록 변경
  frontend/__test__/convertTextToUrl.test.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/post/Post/index.tsx
  frontend/src/components/post/Post/style.ts
  frontend/src/hooks/useText.ts
  frontend/src/utils/post/convertTextToElement.tsx
  frontend/src/utils/post/convertTextToUrl.ts
Labels: FE, 🐾 개발

#708 PostMenu, CommentMenu을 하나의 Menu 컴포넌트로 통합
  frontend/src/components/comment/CommentList/CommentItem/CommentItem.stories.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/CommentMenu.stories.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/style.ts
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/constants.ts
  frontend/src/components/comment/CommentList/index.tsx
  frontend/src/components/comment/CommentList/types.ts
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/index.tsx
  frontend/src/components/common/Menu/style.ts
  frontend/src/components/common/Menu/types.ts
  frontend/src/components/common/PostMenu/PostMenu.stories.tsx
  frontend/src/constants/post.ts
  frontend/src/pages/post/PostDetailPage/InnerHeaderPart/index.tsx
  frontend/src/types/menu.ts
Labels: FE, 🛠 리팩터링

#761 디자인 시스템 설치 및 프로바이더 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
Labels: FE, 🐾 개발

#756 신고조치알림 관련 기능 구현
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmCommandController.java
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmCommandControllerDocs.java
  backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionAlarmResponse.java
  backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionResponse.java
  backend/src/main/java/com/votogether/domain/alarm/entity/ReportActionAlarm.java
  backend/src/main/java/com/votogether/domain/alarm/exception/ReportActionAlarmExceptionType.java
  backend/src/main/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepository.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
  backend/src/main/java/com/votogether/domain/post/controller/PostCommandController.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostOptionVoteResultResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostVoteResultResponse.java
  backend/src/main/java/com/votogether/domain/post/service/PostQueryService.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportRepository.java
  backend/src/test/java/com/votogether/domain/alarm/controller/AlarmCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepositoryTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmServiceTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostQueryServiceTest.java
  backend/src/test/java/com/votogether/domain/report/repository/ReportRepositoryTest.java
Labels: BE, 🐾 개발, 🚨 우선 순위 높음

#750 신고 조치 예정 목록 조회 기능 구현
  backend/src/main/java/com/votogether/domain/report/controller/ReportCommandController.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportQueryController.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportQueryControllerDocs.java
  backend/src/main/java/com/votogether/domain/report/dto/ReportAggregateDto.java
  backend/src/main/java/com/votogether/domain/report/dto/response/ReportPageResponse.java
  backend/src/main/java/com/votogether/domain/report/dto/response/ReportResponse.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportCustomRepository.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportRepository.java
  backend/src/main/java/com/votogether/domain/report/service/ReportCommandService.java
  backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportActionProvider.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportCommentStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportNicknameStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportPostStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportStrategy.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportQueryControllerTest.java
  backend/src/test/java/com/votogether/domain/report/repository/ReportCustomRepositoryImplTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportQueryServiceTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportCommentStrategyTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportNicknameStrategyTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportPostStrategyTest.java
Labels: BE, 🐾 개발

#764 [BUG] 삭제된 addText가 포함된 PR이 머지되어 발생하는 오류 해결
  frontend/src/components/PostForm/CategoryWrapper/index.tsx
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/common/MultiSelect/index.tsx
  frontend/src/hooks/useMultiSelect.ts
Labels: FE, 🐛 버그

#748 [FEAT] 공지사항 관련 기능 구현
  backend/src/main/java/com/votogether/domain/notice/controller/NoticeCommandController.java
  backend/src/main/java/com/votogether/domain/notice/controller/NoticeCommandControllerDocs.java
  backend/src/main/java/com/votogether/domain/notice/controller/NoticeQueryController.java
  backend/src/main/java/com/votogether/domain/notice/controller/NoticeQueryControllerDocs.java
  backend/src/main/java/com/votogether/domain/notice/dto/request/NoticeRequest.java
  backend/src/main/java/com/votogether/domain/notice/dto/response/NoticePageResponse.java
  backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
  backend/src/main/java/com/votogether/domain/notice/entity/Notice.java
  backend/src/main/java/com/votogether/domain/notice/entity/vo/BannerTitle.java
  backend/src/main/java/com/votogether/domain/notice/entity/vo/Detail.java
  backend/src/main/java/com/votogether/domain/notice/exception/NoticeExceptionType.java
  backend/src/main/java/com/votogether/domain/notice/repository/NoticeRepository.java
  backend/src/main/java/com/votogether/domain/notice/service/NoticeCommandService.java
  backend/src/main/java/com/votogether/domain/notice/service/NoticeQueryService.java
  backend/src/test/java/com/votogether/domain/notice/controller/NoticeCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/notice/controller/NoticeQueryControllerTest.java
  backend/src/test/java/com/votogether/domain/notice/repository/NoticeRepositoryTest.java
  backend/src/test/java/com/votogether/domain/notice/service/NoticeCommandServiceTest.java
  backend/src/test/java/com/votogether/domain/notice/service/NoticeQueryServiceTest.java
Labels: BE, 🐾 개발, 🚨 우선 순위 높음

#752 작성시간 | 마감시간이 좁아져서 보이던 문제 해결
  frontend/src/components/post/Post/index.tsx
  frontend/src/components/post/Post/style.ts
  frontend/src/components/post/PostList/style.ts
Labels: FE, 🐛 버그

#765 디자인 시스템의 ResponsiveFlex 컴포넌트를 PostForm 페이지에 적용
  frontend/__test__/hooks/query/notice/usePagedNoticeList.test.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/styles/theme.ts
Labels: FE, 🛠 리팩터링

#755 관리자 신고 목록 페이지 구현
  frontend/__test__/hooks/query/notice/usePagedNoticeList.test.tsx
  frontend/src/api/report.ts
  frontend/src/constants/path.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/report.ts
  frontend/src/hooks/query/report/usePendingReportActionList.ts
  frontend/src/hooks/query/report/useReportAction.ts
  frontend/src/mocks/mockData/report.ts
  frontend/src/mocks/report.ts
  frontend/src/pages/admin/PendingReportPage/PendingReportPage.stories.tsx
  frontend/src/pages/admin/PendingReportPage/index.tsx
  frontend/src/pages/admin/PendingReportPage/stlye.ts
  frontend/src/routes/PrivateRoute.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/report.ts
Labels: FE, 🐾 개발

#749 공지사항 목록 컴포넌트 / 공지사항 상세 컴포넌트 UI 구현 / 공지사항 ROUTER 설정
  frontend/__test__/api/notice.test.ts
  frontend/__test__/hooks/query/notice/useCreateNotice.test.tsx
  frontend/__test__/hooks/query/notice/useModifyNotice.test.tsx
  frontend/src/api/notice.ts
  frontend/src/components/notice/NoticeDetail/NoticeDetail.stories.tsx
  frontend/src/components/notice/NoticeDetail/index.tsx
  frontend/src/components/notice/NoticeDetail/style.ts
  frontend/src/components/notice/NoticeList/NoticeItem/NoticeItem.stories.tsx
  frontend/src/components/notice/NoticeList/NoticeItem/index.tsx
  frontend/src/components/notice/NoticeList/NoticeItem/style.ts
  frontend/src/components/notice/NoticeList/NoticeList.stories.tsx
  frontend/src/components/notice/NoticeList/index.tsx
  frontend/src/components/notice/NoticeList/style.ts
  frontend/src/constants/path.ts
  frontend/src/constants/policyMessage.ts
  frontend/src/hooks/query/notice/useCreateNotice.tsx
  frontend/src/hooks/query/notice/useModifyNotice.tsx
  frontend/src/mocks/mockData/notice.ts
  frontend/src/mocks/mockData/report.ts
  frontend/src/pages/notice/NoticeDetailPage/NoticeDetailPage.stories.tsx
  frontend/src/pages/notice/NoticeDetailPage/index.tsx
  frontend/src/pages/notice/NoticeDetailPage/style.ts
  frontend/src/pages/notice/NoticeListPage/NoticeListPage.stories.tsx
  frontend/src/pages/notice/NoticeListPage/index.tsx
  frontend/src/pages/notice/NoticeListPage/style.ts
  frontend/src/routes/router.tsx
  frontend/src/types/notice.ts
  frontend/src/types/time.ts
Labels: FE, 🐾 개발

#773 다른 사람의 알림까지 보이는 문제 해결
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmCommandControllerDocs.java
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmQueryController.java
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmQueryControllerDocs.java
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmQueryQueryController.java
  backend/src/main/java/com/votogether/domain/alarm/repository/AlarmRepository.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmQueryService.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/test/java/com/votogether/domain/alarm/controller/AlarmCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/alarm/controller/AlarmQueryControllerTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmEventListenerTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmQueryServiceTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmServiceTest.java
  backend/src/test/resources/truncate.sql
Labels: BE, 🐛 버그

#754 공지사항 목록 페이지 이동 링크 추가 / 마이페이지에 공지사항, 관리자 페이지 추가
  frontend/__test__/api/user.test.ts
  frontend/package-lock.json
  frontend/src/components/common/Dashboard/CategorySection/style.ts
  frontend/src/components/common/Dashboard/GuestProfile/index.tsx
  frontend/src/components/common/Dashboard/GuestProfile/style.ts
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/components/common/Dashboard/style.ts
  frontend/src/constants/path.ts
  frontend/src/mocks/mockData/user.ts
  frontend/src/mocks/userInfo.ts
  frontend/src/pages/MyInfoPage/index.tsx
  frontend/src/pages/MyInfoPage/style.ts
  frontend/src/pages/admin/PendingReportPage/index.tsx
  frontend/src/pages/auth/LoginPage/MobileLogin/index.tsx
  frontend/src/pages/auth/LoginPage/MobileLogin/style.ts
  frontend/src/routes/PrivateRoute.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🐾 개발

#776 [BUG] 알림이 비회원일때도 api요청을 해서 에러가 뜹니다
  frontend/src/components/AlarmContainer/ListStyle.ts
  frontend/src/components/common/NarrowMainHeader/style.ts
  frontend/src/components/common/WideHeader/index.tsx
  frontend/src/hooks/query/alarm/useReadAlarm.ts
  frontend/src/hooks/query/user/useReadLatestAlarm.ts
  frontend/src/pages/HomePage/index.tsx
Labels: FE, 🐛 버그

#770 신고 조치 기능 구현
  backend/src/main/java/com/votogether/domain/member/dto/response/MemberInfoResponse.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/vo/Role.java
  backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportCommandController.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportCommandControllerDocs.java
  backend/src/main/java/com/votogether/domain/report/dto/request/ReportActionRequest.java
  backend/src/main/java/com/votogether/domain/report/exception/ReportExceptionType.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportCustomRepository.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/report/service/ReportCommandService.java
  backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportCommentStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportNicknameStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportPostStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportStrategy.java
  backend/src/test/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportQueryControllerTest.java
  backend/src/test/java/com/votogether/domain/report/repository/ReportCustomRepositoryImplTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportCommandServiceTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportQueryServiceTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportCommentStrategyTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportNicknameStrategyTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportPostStrategyTest.java
  backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
  backend/src/test/java/com/votogether/test/fixtures/MemberFixtures.java
  backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
Labels: BE, 🐾 개발

#777 랭킹 저화질 이미지를 고화질 이미지로 바꿔 프로젝트 완성도를 높인다
  frontend/src/assets/first-rank.webp
  frontend/src/assets/ranking-first.webp
  frontend/src/assets/ranking-second.webp
  frontend/src/assets/ranking-third.webp
  frontend/src/assets/second-rank.webp
  frontend/src/assets/third-rank.webp
  frontend/src/components/common/ToggleSwitch/style.ts
  frontend/src/pages/RankingPage/PageContent/index.tsx
  frontend/src/pages/RankingPage/PassionUser/UserRanking/index.tsx
  frontend/src/pages/RankingPage/PassionUser/index.tsx
  frontend/src/pages/RankingPage/PassionUser/style.ts
  frontend/src/pages/RankingPage/PopularPost/index.tsx
  frontend/src/pages/RankingPage/PopularPost/style.ts
  frontend/src/pages/RankingPage/RankingTableStyle.ts
  frontend/src/pages/RankingPage/style.ts
Labels: FE, 🐛 버그

#775 알림 읽기 기능 구현
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmCommandController.java
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmCommandControllerDocs.java
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmQueryController.java
  backend/src/main/java/com/votogether/domain/alarm/controller/AlarmQueryControllerDocs.java
  backend/src/main/java/com/votogether/domain/alarm/entity/Alarm.java
  backend/src/main/java/com/votogether/domain/alarm/entity/ReportActionAlarm.java
  backend/src/main/java/com/votogether/domain/alarm/entity/vo/AlarmActionType.java
  backend/src/main/java/com/votogether/domain/alarm/exception/AlarmExceptionType.java
  backend/src/main/java/com/votogether/domain/alarm/exception/ReportActionAlarmExceptionType.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmCommandService.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmQueryService.java
  backend/src/main/java/com/votogether/domain/alarm/service/strategy/AlarmReadStrategy.java
  backend/src/main/java/com/votogether/domain/alarm/service/strategy/AlarmReadStrategyProvider.java
  backend/src/main/java/com/votogether/domain/alarm/service/strategy/ContentAlarmReadStrategy.java
  backend/src/main/java/com/votogether/domain/alarm/service/strategy/ReportAlarmReadStrategy.java
  backend/src/main/java/com/votogether/domain/member/dto/response/MemberInfoResponse.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/vo/Roles.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportCommandControllerDocs.java
  backend/src/main/java/com/votogether/domain/report/dto/response/ReportResponse.java
  backend/src/main/java/com/votogether/domain/report/exception/ReportExceptionType.java
  backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
  backend/src/test/java/com/votogether/domain/alarm/controller/AlarmCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/alarm/entity/AlarmTest.java
  backend/src/test/java/com/votogether/domain/alarm/entity/ReportActionAlarmTest.java
  backend/src/test/java/com/votogether/domain/alarm/entity/vo/AlarmActionTypeTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmCommandServiceTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmEventListenerTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmQueryServiceTest.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportCommandServiceTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportQueryServiceTest.java
  backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
  backend/src/test/java/com/votogether/test/fixtures/MemberFixtures.java
  backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
Labels: BE, 🐾 개발, 🚨 우선 순위 높음

#758 발생하는 쿼리 확인 후 쿼리 성능 개선
  backend/src/main/java/com/votogether/domain/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/votogether/domain/category/exception/CategoryExceptionType.java
  backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
  backend/src/main/java/com/votogether/domain/member/dto/response/MemberInfoResponse.java
  backend/src/main/java/com/votogether/domain/member/entity/MemberMetric.java
  backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberMetricCustomRepository.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberMetricCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberMetricRepository.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostSummaryResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostVoteResultResponse.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/post/repository/PostOptionRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/dto/PostCommentCountDto.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/main/java/com/votogether/domain/post/service/PostGuestService.java
  backend/src/main/java/com/votogether/domain/post/service/PostQueryService.java
  backend/src/main/java/com/votogether/domain/ranking/dto/response/RankingResponse.java
  backend/src/main/java/com/votogether/domain/ranking/entity/PassionRankings.java
  backend/src/main/java/com/votogether/domain/ranking/entity/vo/PassionRecord.java
  backend/src/main/java/com/votogether/domain/ranking/service/RankingService.java
  backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
  backend/src/test/java/com/votogether/domain/category/service/CategoryServiceTest.java
  backend/src/test/java/com/votogether/domain/member/entity/PassionRankingsTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/post/repository/CommentRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostCustomRepositoryImplTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostCommandServiceTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostGuestServiceTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostQueryServiceTest.java
  backend/src/test/java/com/votogether/domain/ranking/service/RankingServiceTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
  backend/src/test/java/com/votogether/domain/vote/service/VoteServiceConcurrentTest.java
  backend/src/test/java/com/votogether/domain/vote/service/VoteServiceTest.java
  backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
  backend/src/test/java/com/votogether/test/RepositoryTest.java
  backend/src/test/java/com/votogether/test/ServiceTest.java
  backend/src/test/java/com/votogether/test/persister/MemberMetricTestPersister.java
  backend/src/test/java/com/votogether/test/persister/PostTestPersister.java
Labels: BE, 🛠 리팩터링, 📄 문서, 🚨 우선 순위 높음

#780 공지사항 목록 관리자 페이지 구현 / 공지사항 생성, 수정, 삭제 기능
  frontend/__test__/hooks/query/notice/usePagedNoticeList.test.tsx
  frontend/__test__/hooks/usePagination.test.tsx
  frontend/package-lock.json
  frontend/src/components/notice/AdminNoticeEdit/AdminNoticeEdit.stories.tsx
  frontend/src/components/notice/AdminNoticeEdit/index.tsx
  frontend/src/components/notice/AdminNoticeTableFetcher/AdminNoticeTableFetcher.stories.tsx
  frontend/src/components/notice/AdminNoticeTableFetcher/index.tsx
  frontend/src/components/notice/AdminNoticeTableFetcher/style.ts
  frontend/src/components/notice/NoticeForm/constant.ts
  frontend/src/components/notice/NoticeForm/index.tsx
  frontend/src/components/notice/NoticeForm/style.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/index.tsx
  frontend/src/hooks/query/notice/usePagedNoticeList.tsx
  frontend/src/hooks/usePagination.ts
  frontend/src/mocks/mockData/notice.ts
  frontend/src/pages/admin/notices/NoticeAdminPage/NoticeAdminPage.stories.tsx
  frontend/src/pages/admin/notices/NoticeAdminPage/index.tsx
  frontend/src/pages/admin/notices/NoticeAdminPage/style.ts
  frontend/src/pages/admin/notices/NoticeEditPage/NoticeEditPage.stories.tsx
  frontend/src/pages/admin/notices/NoticeEditPage/index.tsx
  frontend/src/pages/admin/notices/NoticeWritePage/NoticeWritePage.stories.tsx
  frontend/src/pages/admin/notices/NoticeWritePage/index.tsx
  frontend/src/routes/PrivateRoute.tsx
  frontend/src/routes/router.tsx
  frontend/src/utils/post/addTimeToDate.ts
Labels: FE, 🐾 개발

#784 커넥션풀 관련 설정 추가 + 회원탈퇴시 fk 관련 삭제 로직 추가
  backend/src/main/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepository.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmQueryService.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/notice/repository/NoticeRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/alarm/controller/AlarmQueryControllerTest.java
  backend/src/test/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🛠 리팩터링, 🐛 버그

#783 최신 알림 존재 여부 및 읽기 기능 구현
  backend/src/main/java/com/votogether/domain/alarm/entity/Alarm.java
  backend/src/main/java/com/votogether/domain/alarm/exception/AlarmExceptionType.java
  backend/src/main/java/com/votogether/domain/alarm/repository/AlarmRepository.java
  backend/src/main/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepository.java
  backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
  backend/src/main/java/com/votogether/domain/member/controller/MemberControllerDocs.java
  backend/src/main/java/com/votogether/domain/member/dto/response/MemberInfoResponse.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/test/java/com/votogether/domain/alarm/entity/AlarmTest.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/entity/MemberTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/test/fixtures/MemberFixtures.java
  backend/src/test/java/com/votogether/test/persister/AlarmTestPersister.java
  backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
  backend/src/test/java/com/votogether/test/persister/ReportActionAlarmTestPersister.java
Labels: BE, 🐾 개발, 🚨 우선 순위 높음

#781 [BUG] 모바일 비회원일 때 신고 버튼을 눌르면 알 수 없는 에러 메세지입니다라고 떠요
  frontend/src/components/ReportModal/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/hooks/query/report/useReportAction.ts
  frontend/src/hooks/query/report/useReportContent.ts
  frontend/src/pages/post/PostDetailPage/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetailPage/InnerHeaderPart/InnerHeaderPart.stories.tsx
  frontend/src/pages/post/PostDetailPage/InnerHeaderPart/index.tsx
  frontend/src/pages/post/PostDetailPage/PostDetail/index.tsx
Labels: FE, 🐛 버그

#721 TwoButtonModal을 기존의 Modal 컴포넌트로 대체
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/ReportModal/ReportModal.stories.tsx
  frontend/src/components/ReportModal/index.tsx
  frontend/src/components/ReportModal/style.ts
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/common/Accordion/Accordion.stories.tsx
  frontend/src/components/common/DeleteModal/index.tsx
  frontend/src/components/common/DeleteModal/style.ts
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/Modal/style.ts
  frontend/src/components/common/TimePickerOptionList/style.ts
  frontend/src/components/common/TwoButtonModal/index.tsx
  frontend/src/components/common/TwoButtonModal/style.ts
  frontend/src/pages/MyInfoPage/DeleteMemberModal/index.tsx
  frontend/src/pages/MyInfoPage/DeleteMemberModal/style.ts
  frontend/src/pages/post/PostDetailPage/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetailPage/InnerHeaderPart/index.tsx
Labels: FE, 🛠 리팩터링, 🐛 버그

#779 알림 읽기 api를 content와 report로 분리함에 따라 코드 수정
  frontend/src/api/alarm.ts
  frontend/src/components/AlarmContainer/ContentAlarmList/index.tsx
  frontend/src/components/AlarmContainer/ReportAlarmList/index.tsx
  frontend/src/hooks/query/alarm/useReadAlarm.ts
  frontend/src/mocks/mockData/alarm.ts
  frontend/src/styles/globalStyle.ts
  frontend/src/types/alarm.ts
Labels: FE, 🐾 개발

#787 공지사항 목록 페이지 / 공지사항 상세 페이지 / 공지사항 배너 데이터 패치하기 / 배너 닫기 쿠키 설정 / dynamic import 적용
  frontend/src/api/notice.ts
  frontend/src/components/common/AppInstallPrompt/index.tsx
  frontend/src/components/common/Banner/style.ts
  frontend/src/components/common/Skeleton/style.ts
  frontend/src/components/notice/AdminNoticeEdit/index.tsx
  frontend/src/components/notice/BannerFetcher/index.tsx
  frontend/src/components/notice/BannerSkeleton/index.tsx
  frontend/src/components/notice/BannerSkeleton/style.ts
  frontend/src/components/notice/NoticeDetail/index.tsx
  frontend/src/components/notice/NoticeDetail/style.ts
  frontend/src/components/notice/NoticeDetailFetcher/index.tsx
  frontend/src/components/notice/NoticeListFetcher/index.tsx
  frontend/src/components/notice/NoticeListFetcher/style.ts
  frontend/src/constants/cookie.ts
  frontend/src/constants/path.ts
  frontend/src/constants/policyMessage.ts
  frontend/src/hooks/query/notice/useBannerNotice.tsx
  frontend/src/hooks/query/notice/useCreateNotice.tsx
  frontend/src/hooks/query/notice/useDeleteNotice.tsx
  frontend/src/hooks/query/notice/useModifyNotice.tsx
  frontend/src/hooks/query/notice/useNoticeDetail.tsx
  frontend/src/hooks/query/notice/usePagedNoticeList.tsx
  frontend/src/hooks/query/notice/useStackedNoticeList.tsx
  frontend/src/hooks/useBannerToggle.ts
  frontend/src/mocks/mockData/notice.ts
  frontend/src/pages/AnnouncementPage/index.tsx
  frontend/src/pages/AnnouncementPage/style.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/NoRenderErrorBoundary.tsx
  frontend/src/pages/admin/notices/NoticeWritePage/index.tsx
  frontend/src/pages/notice/NoticeDetailPage/index.tsx
  frontend/src/pages/notice/NoticeDetailPage/style.ts
  frontend/src/pages/notice/NoticeListPage/index.tsx
  frontend/src/pages/notice/NoticeListPage/style.ts
  frontend/src/routes/router.tsx
  frontend/src/types/notice.ts
  frontend/src/utils/cookie.ts
Labels: FE, 🐾 개발

#790 가장 최신 값을 가져오도록 data jpa 메서드명 변경
  backend/src/main/java/com/votogether/domain/alarm/repository/AlarmRepository.java
  backend/src/main/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepository.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
Labels: BE, 🐛 버그

#800 @JsonFormat 추가
  backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
  backend/src/test/java/com/votogether/domain/notice/controller/NoticeQueryControllerTest.java
Labels: BE, 🐛 버그

#803 댓글 작성 시 알림 추가 기능 버그 수정
  backend/src/main/java/com/votogether/domain/alarm/dto/event/PostAlarmEvent.java
  backend/src/main/java/com/votogether/domain/alarm/dto/response/PostAlarmDetailResponse.java
  backend/src/main/java/com/votogether/domain/alarm/dto/response/PostAlarmResponse.java
  backend/src/main/java/com/votogether/domain/alarm/entity/Alarm.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmEventListener.java
  backend/src/main/java/com/votogether/domain/alarm/service/AlarmQueryService.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmCommandServiceTest.java
  backend/src/test/java/com/votogether/domain/alarm/service/AlarmEventListenerTest.java
  backend/src/test/java/com/votogether/test/persister/AlarmTestPersister.java
Labels: BE, 🐛 버그

#802 공지사항 생성, 수정, 삭제 시 캐시 초기화 로직 변경
  frontend/src/api/notice.ts
  frontend/src/hooks/query/notice/useCreateNotice.tsx
  frontend/src/hooks/query/notice/useDeleteNotice.tsx
  frontend/src/hooks/query/notice/useModifyNotice.tsx
  frontend/src/mocks/notice.ts
Labels: FE, 🐛 버그

#805 이벤트 준비
  frontend/package-lock.json
  frontend/src/api/alarm.ts
  frontend/src/assets/dangseon-yo.png
  frontend/src/assets/dangseon.png
  frontend/src/components/common/LogoButton/index.tsx
  frontend/src/components/common/UpButton/index.tsx
  frontend/src/components/common/UpButton/style.ts
  frontend/src/hooks/query/user/useUserInfo.ts
  frontend/src/mocks/mockData/reportApproveResult.ts
  frontend/src/pages/EventMascot/index.tsx
  frontend/src/pages/EventMascot/style.ts
  frontend/src/types/time.ts
  frontend/src/utils/post/addTimeToDate.ts
Labels: FE, 🐾 개발, 🐛 버그

#804 신고 목록 조회 response 값이 UI에 보이지 않도록 response 를 가공하여 보여주도록 수정
  frontend/__test__/hooks/usePagination.test.tsx
  frontend/src/api/report.ts
  frontend/src/hooks/query/notice/useStackedNoticeList.tsx
  frontend/src/mocks/mockData/report.ts
  frontend/src/pages/admin/PendingReportPage/index.tsx
Labels: FE, 🐛 버그

#807 필터에서 notices url 수정
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
Labels: BE, 🐛 버그

#819 Release v.1.3.1
  backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
  frontend/__test__/convertTextToUrl.test.ts
  frontend/src/assets/dangseon-yo.png
  frontend/src/assets/dangseon.png
  frontend/src/components/AlarmContainer/style.ts
  frontend/src/components/common/LogoButton/index.tsx
  frontend/src/components/common/ToolTip/style.ts
  frontend/src/components/common/UpButton/index.tsx
  frontend/src/components/common/UpButton/style.ts
  frontend/src/components/post/Post/style.ts
  frontend/src/pages/EventMascot/index.tsx
  frontend/src/pages/EventMascot/style.ts
  frontend/src/styles/reset.ts
  frontend/src/utils/post/convertTextToUrl.ts
Labels: BE, FE

#821 cypress를 이용한 e2e test 도입
  frontend/cypress.config.ts
  frontend/cypress.d.ts
  frontend/cypress/.eslintrc.json
  frontend/cypress/e2e/guestFeatureTest.cy.ts
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: FE, 👷🏻 테스트

#826 safari에서 작동되지 않거나 의도한대로 보이지 않는 부분 수정 및 기타 이슈
  frontend/__test__/hooks/usePagination.test.tsx
  frontend/src/components/common/ImageZoomModal/style.ts
  frontend/src/components/common/MultiSelect/style.ts
  frontend/src/pages/auth/LoginPage/MobileLogin/style.ts
Labels: FE, 🐛 버그
