Repository woowacourse-teams/2023-votogether, pull requests merged in 2023-09, with the labels that each got.

#458 타임 픽커 웹 접근성 향상
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/constants.ts
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/index.tsx
  frontend/src/components/common/TimePickerOptionList/index.tsx
Labels: FE, 🛠 리팩터링

#455 Accordion, AddButton, Modal, TwoButtonModal, DeleteModal 웹접근성 높이기
  frontend/src/components/common/Accordion/Accordion.stories.tsx
  frontend/src/components/common/Accordion/index.tsx
  frontend/src/components/common/AddButton/AddButton.stories.tsx
  frontend/src/components/common/DeleteModal/index.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/Modal/style.ts
  frontend/src/components/common/TwoButtonModal/index.tsx
Labels: FE, 🛠 리팩터링

#506 랭킹 시스템 패치 함수 및 훅 만들기
  frontend/src/api/ranking.ts
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/query/ranking/usePassionUserRanking.ts
  frontend/src/hooks/query/ranking/usePopularPostRanking.ts
  frontend/src/hooks/query/ranking/useUserRanking.ts
  frontend/src/types/ranking.ts
Labels: FE, 🐾 개발

#503 구글 태그 및 채널톡 버튼 추가, 코드리뷰 마감시간 알림 슬랙봇 구현
  .github/workflows/backend-pr-comment.yml
  .github/workflows/backend-pr-deadline-slack-bot.yml
  .github/workflows/frontend-pr-comment.yml
  .github/workflows/frontend-pr-deadline-slack-bot.yml
  .github/workflows/frontend-storybook-deploy.yml
  .github/workflows/scripts/calculatePRDeadline.js
  frontend/__test__/calculatePRDeadline.test.ts
  frontend/env.d.ts
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/ChannelTalk/index.tsx
Labels: FE, 🐾 개발, 🐳 인프라

#460 대시보드 컴포넌트, 통계 컴포넌트, UpButton 웹접근성 높이기
  frontend/src/components/VoteStatistics/OneLineGraph/index.tsx
  frontend/src/components/VoteStatistics/TwoLineGraph/index.tsx
  frontend/src/components/VoteStatistics/index.tsx
  frontend/src/components/common/Dashboard/GuestProfile/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/components/common/Dashboard/profileStyle.ts
  frontend/src/components/common/UpButton/index.tsx
  frontend/src/pages/VoteStatisticsPage/OptionStatistics/index.tsx
  frontend/src/pages/VoteStatisticsPage/OptionStatistics/style.ts
Labels: FE, 🛠 리팩터링

#499 랭킹 시스템 UI 구현 및 내정보 페이지로 가는 UI 추가, 랭킹페이지로 이동하는 UI 생성
  frontend/src/assets/first-rank.svg
  frontend/src/assets/ranking.svg
  frontend/src/assets/retry.svg
  frontend/src/assets/second-rank.svg
  frontend/src/assets/third-rank.svg
  frontend/src/assets/user.svg
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/IconButton/IconButton.stories.tsx
  frontend/src/components/common/IconButton/index.tsx
  frontend/src/components/common/IconButton/style.ts
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/NarrowMainHeader/NarrowMainHeader.stories.tsx
  frontend/src/components/common/NarrowMainHeader/index.tsx
  frontend/src/components/common/ToggleSwitch/ToggleSwitch.stories.tsx
  frontend/src/components/common/ToggleSwitch/index.tsx
  frontend/src/components/common/ToggleSwitch/style.ts
  frontend/src/components/common/WideHeader/WideHeader.stories.tsx
  frontend/src/components/common/WideHeader/index.tsx
  frontend/src/components/common/WideHeader/style.ts
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/constants/path.ts
  frontend/src/hooks/useToggleSwitch.ts
  frontend/src/pages/Ranking/PassionUser/PassionUser.stories.tsx
  frontend/src/pages/Ranking/PassionUser/index.tsx
  frontend/src/pages/Ranking/PassionUser/style.ts
  frontend/src/pages/Ranking/PopularPost/PopularPost.stories.tsx
  frontend/src/pages/Ranking/PopularPost/index.tsx
  frontend/src/pages/Ranking/PopularPost/style.ts
  frontend/src/pages/Ranking/Ranking.stories.tsx
  frontend/src/pages/Ranking/RankingTableStyle.ts
  frontend/src/pages/Ranking/index.tsx
  frontend/src/pages/Ranking/style.ts
  frontend/src/routes/router.tsx
Labels: FE, 🐾 개발

#451 게시글 컴포넌트, 댓글 컴포넌트, PostMenu 컴포넌트 웹접근성 높이기
  frontend/package.json
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/style.ts
  frontend/src/components/comment/CommentList/CommentLoginSection/index.tsx
  frontend/src/components/comment/CommentList/CommentLoginSection/style.ts
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/comment/CommentList/index.tsx
  frontend/src/components/comment/CommentList/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Toast/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/index.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
  frontend/src/pages/post/PostDetail/PostDetail/style.ts
  frontend/src/styles/globalStyle.ts
Labels: FE, 🐾 개발

#525 랭킹 UI와 hook 연결 및 msw 도입 (+변경된 랭킹 객체 타입 적용)
  frontend/src/api/ranking.ts
  frontend/src/hooks/query/ranking/usePassionUserRanking.ts
  frontend/src/hooks/query/ranking/usePopularPostRanking.ts
  frontend/src/hooks/query/ranking/useUserRanking.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/ranking.ts
  frontend/src/pages/Ranking/PassionUser/PassionUser.stories.tsx
  frontend/src/pages/Ranking/PassionUser/UserRanking/index.tsx
  frontend/src/pages/Ranking/PassionUser/index.tsx
  frontend/src/pages/Ranking/PassionUser/style.ts
  frontend/src/pages/Ranking/PopularPost/PopularPost.stories.tsx
  frontend/src/pages/Ranking/PopularPost/index.tsx
  frontend/src/pages/Ranking/RankingTableStyle.ts
  frontend/src/pages/Ranking/index.tsx
  frontend/src/types/ranking.ts
Labels: FE, 🐾 개발

#529 닉네임 정책 사용자에게 14일마다 가능하다고 안내 메세지 변경
  frontend/src/constants/policyMessage.ts
  frontend/src/index.tsx
  frontend/src/pages/MyInfo/index.tsx
Labels: FE, 🐾 개발

#498 회원의 닉네임을 일정주기를 통해 변경할 수 있도록 구현
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/vo/Nickname.java
  backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/test/java/com/votogether/domain/member/entity/MemberTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
Labels: BE, 🐾 개발

#544 ts-loader를 esbuild-loader로 마이그레이션(빌드 시간 최적화)
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
Labels: FE, 🛠 리팩터링

#562 불필요한 플러그인(webpack-bundle-analyzer) 삭제하여 github action 무한 로딩 해결
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
Labels: FE, 🐛 버그

#547 검색에 관한 설정과 전체 게시글 초기 설정 변경
  frontend/__test__/getSelectedState.test.ts
  frontend/__test__/getTrimmedWord.test.ts
  frontend/__test__/hooks/useSearch.test.tsx
  frontend/__test__/hooks/useSelect.test.tsx
  frontend/src/components/common/Dashboard/CategorySection/index.tsx
  frontend/src/components/common/SearchBar/index.tsx
  frontend/src/hooks/context/postOption.tsx
  frontend/src/hooks/useCurrentKeyword.ts
  frontend/src/hooks/usePostRequestInfo.ts
  frontend/src/hooks/useSearch.ts
  frontend/src/hooks/useText.ts
  frontend/src/utils/getTrimmedWord.ts
  frontend/src/utils/post/getSelectedState.ts
Labels: FE, 🐾 개발

#546 인기게시글 랭킹 목록 조회 기능
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/controller/PostControllerDocs.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostRankingResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostSummaryResponse.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#569 열정 유저 랭킹 목록 조회 기능
  backend/src/main/java/com/votogether/domain/ranking/controller/RankingController.java
  backend/src/main/java/com/votogether/domain/ranking/controller/RankingControllerDocs.java
  backend/src/main/java/com/votogether/domain/ranking/dto/response/RankingResponse.java
  backend/src/main/java/com/votogether/domain/ranking/entity/PassionRankings.java
  backend/src/main/java/com/votogether/domain/ranking/service/RankingService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/ranking/controller/RankingControllerTest.java
  backend/src/test/java/com/votogether/domain/ranking/service/RankingServiceTest.java
Labels: BE, 🐾 개발

#545 리프레시 토큰 기능(로그아웃 포함) 구현
  backend/build.gradle
  backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
  backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
  backend/src/main/java/com/votogether/domain/auth/dto/request/AccessTokenRequest.java
  backend/src/main/java/com/votogether/domain/auth/dto/response/LoginResponse.java
  backend/src/main/java/com/votogether/domain/auth/dto/response/OAuthAccessTokenResponse.java
  backend/src/main/java/com/votogether/domain/auth/dto/response/ReissuedAccessTokenResponse.java
  backend/src/main/java/com/votogether/domain/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/main/java/com/votogether/domain/auth/service/dto/LoginTokenDto.java
  backend/src/main/java/com/votogether/domain/auth/service/dto/ReissuedTokenDto.java
  backend/src/main/java/com/votogether/domain/auth/service/dto/TokenPayloadDto.java
  backend/src/main/java/com/votogether/global/config/RedisConfig.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
  backend/src/main/java/com/votogether/global/jwt/exception/JsonException.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/votogether/domain/auth/service/AuthServiceTest.java
  backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
  backend/src/test/java/com/votogether/test/config/RedisTestConfig.java
  backend/src/test/resources/application.yml
Labels: BE, 🐾 개발

#575 TestContainer로 인한 빌드 불가 상태로 임시 test 삭제
  backend/src/test/java/com/votogether/domain/auth/service/AuthServiceTest.java
Labels: BE, 🐾 개발

#517 리프레시 토큰 구현
  frontend/__test__/api/postTokens.test.ts
  frontend/__test__/api/user.test.ts
  frontend/__test__/isExpiredAccessToken.test.ts
  frontend/__test__/isExpiredRefreshToken.test.ts
  frontend/__test__/isRefreshTokenRequested.test.ts
  frontend/__test__/slientLogin.test.ts
  frontend/src/api/token.ts
  frontend/src/api/userInfo.ts
  frontend/src/components/common/AppInstallPrompt/index.tsx
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/constants/cookie.ts
  frontend/src/constants/localStorage.ts
  frontend/src/constants/token.ts
  frontend/src/hooks/context/auth.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/mockData/token.ts
  frontend/src/mocks/token.ts
  frontend/src/mocks/userInfo.ts
  frontend/src/pages/MyInfo/index.tsx
  frontend/src/pages/auth/Redirection.tsx
  frontend/src/pages/user/RegisterPersonalInfo/index.tsx
  frontend/src/routes/PrivateRoute.tsx
  frontend/src/types/token.ts
  frontend/src/types/user.ts
  frontend/src/utils/cookie/index.ts
  frontend/src/utils/fetch.ts
  frontend/src/utils/localStorage.ts
  frontend/src/utils/post/checkWriter.ts
  frontend/src/utils/time.ts
  frontend/src/utils/token/decodeToken.ts
  frontend/src/utils/token/isExpiredAccessToken.ts
  frontend/src/utils/token/isExpiredRefreshToken.ts
  frontend/src/utils/token/isRefreshTokenRequested.ts
  frontend/src/utils/token/silentLogin.ts
Labels: FE, 🐾 개발

#578 response 필드 변수 수정
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostRankingResponse.java
Labels: BE, 🐛 버그

#572 Banner 컴포넌트, 공지사항 페이지 구현
  frontend/src/components/common/Banner/Banner.stories.tsx
  frontend/src/components/common/Banner/index.tsx
  frontend/src/components/common/Banner/style.ts
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/components/post/PostListPage/style.ts
  frontend/src/constants/announcement.ts
  frontend/src/constants/path.ts
  frontend/src/hooks/useToggle.tsx
  frontend/src/pages/Announcement/index.tsx
  frontend/src/pages/Announcement/style.ts
  frontend/src/routes/router.tsx
Labels: FE, 🐾 개발

#597 seo를 위한 sitemap.xml, robots.txt 설정
  frontend/package.json
  frontend/public/index.html
  frontend/public/seo/robots.txt
  frontend/public/seo/sitemap.xml
  frontend/src/utils/generateSiteMap.js
  frontend/webpack.common.js
Labels: FE, 🐾 개발

#593 구글 태그 인식을 위한 script 코드 추가, 사이드바에서 Toast가 잘려 보이는 이슈 해결
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/GoogleTagManager/index.tsx
  frontend/src/components/common/Drawer/style.ts
Labels: FE, 🐛 버그

#601 CORS Credential설정 및 cookie samesite설정
  backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
  backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
Labels: BE, 🐾 개발

#600 로그인 시 쿠키를 주고 받을 수 있도록 fetch 설정 변경
  frontend/src/api/auth.ts
  frontend/src/pages/auth/Redirection.tsx
  frontend/src/utils/fetch.ts
Labels: FE, 🐛 버그

#610 cookie의 path를 /auth에서 /로 변경 및 RefreshToken TTL설정
  backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
Labels: BE, 🐛 버그

#613 구글 애널리틱스 작동을 위한 모듈 설치, 게시글 본문의 링크 클릭 가능하도록 구현
  frontend/env.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/GoogleTagManager/index.tsx
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/RouteChangeTracker/index.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/hooks/useText.ts
  frontend/src/index.tsx
  frontend/src/pages/Announcement/index.tsx
  frontend/src/routes/router.tsx
  frontend/src/utils/post/formatContentLink.tsx
Labels: FE, 🐾 개발, 🐛 버그

#571 로그인, 투표 통계, 회원정보 페이지 lazy import 적용
  frontend/public/seo/sitemap.xml
  frontend/src/App.tsx
  frontend/src/routes/router.tsx
  frontend/webpack.common.js
Labels: FE, 🐾 개발

#614 게시글 작성 시 이미지 파일을 보낼 때 webp 로 압축하여 성능 개선
  frontend/package.json
  frontend/src/hooks/useContentImage.ts
  frontend/src/hooks/useWritingOption.tsx
  frontend/src/utils/resizeImage.ts
Labels: FE, 🐾 개발

#615 Release 1.1.1 출시
  backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  frontend/env.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/seo/sitemap.xml
  frontend/src/App.tsx
  frontend/src/components/GoogleTagManager/index.tsx
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/RouteChangeTracker/index.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/hooks/useContentImage.ts
  frontend/src/hooks/useText.ts
  frontend/src/hooks/useWritingOption.tsx
  frontend/src/index.tsx
  frontend/src/pages/Announcement/index.tsx
  frontend/src/routes/router.tsx
  frontend/src/utils/post/formatContentLink.tsx
  frontend/src/utils/resizeImage.ts
  frontend/webpack.common.js
Labels: BE, FE

#540 신고 도메인 리팩터링
  backend/src/main/java/com/votogether/domain/post/entity/comment/Content.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportCommandCommandController.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportCommandControllerDocs.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportRepository.java
  backend/src/main/java/com/votogether/domain/report/service/ReportCommandService.java
  backend/src/main/java/com/votogether/domain/report/service/ReportService.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportCommentStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportNicknameStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportPostStrategy.java
  backend/src/main/java/com/votogether/domain/report/service/strategy/ReportStrategy.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/post/repository/CommentRepositoryTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
  backend/src/test/java/com/votogether/domain/report/repository/ReportRepositoryTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportCommandServiceTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportCommentStrategyTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportNicknameStrategyTest.java
  backend/src/test/java/com/votogether/domain/report/service/strategy/ReportPostStrategyTest.java
  backend/src/test/java/com/votogether/test/persister/CommentTestPersister.java
  backend/src/test/java/com/votogether/test/persister/PostTestPersister.java
  backend/src/test/java/com/votogether/test/persister/ReportTestPersister.java
Labels: BE, 🛠 리팩터링

#623 정사각형으로 나오는 이미지를 너비값 기준으로 보이게 변경
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/src/components/PostForm/ContentImageSection/style.ts
  frontend/src/components/common/Post/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
  frontend/src/pages/auth/Login/ServiceIntroductionSection/ServiceIntroductionSection.stories.tsx
  frontend/src/pages/auth/Login/ServiceIntroductionSection/StartUsingOurService.stories.tsx
Labels: FE, 🛠 리팩터링

#625 선택지가 왼쪽으로 움직이는 버그 수정
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/style.ts
Labels: FE, 🐛 버그

#630 https 로컬호스트 오리진 url 추가
  backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
Labels: BE, 🐾 개발

#624 게시글 작성 시 이미지 복사 붙혀넣기로 이미지 첨부 가능하도록 구현
  frontend/src/components/PostForm/index.tsx
  frontend/src/hooks/useContentImage.ts
  frontend/src/hooks/useWritingOption.tsx
  frontend/src/utils/post/uploadImage.ts
Labels: FE, 🛠 리팩터링, 🐾 개발

#632 https로 실행되도록 설정 및 스크립트 명령어 추가
  frontend/.gitignore
  frontend/package.json
  frontend/webpack.https.js
Labels: FE, 🐾 개발, 🐳 인프라

#645 [BUG] 게시글 이미지 저장이 되지 않는 문제
  backend/src/main/java/com/votogether/domain/post/controller/PostGuestController.java
  backend/src/main/java/com/votogether/domain/post/controller/PostGuestControllerDocs.java
  backend/src/main/java/com/votogether/domain/post/dto/request/post/PostOptionCreateRequest.java
  backend/src/main/java/com/votogether/domain/post/dto/response/post/PostOptionVoteResultResponse.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
  backend/src/main/java/com/votogether/domain/post/service/PostGuestService.java
  backend/src/main/java/com/votogether/infra/image/ImageName.java
  backend/src/main/java/com/votogether/infra/image/LocalUploader.java
  backend/src/test/java/com/votogether/domain/post/controller/PostGuestControllerTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostGuestServiceTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostQueryServiceTest.java
  backend/src/test/java/com/votogether/infra/image/LocalUploaderTest.java
Labels: BE, 🐛 버그

#557 게시글 작성 api에서 사진을 없는 경우 empty file을 보내는 방식 수정 및 수정 관련 버그 수정
  backend/src/main/java/com/votogether/infra/image/LocalUploader.java
  frontend/__test__/convertTimeToWord.test.ts
  frontend/__test__/deleteOverlappingNewLine.test.ts
  frontend/__test__/getSelectedTimeOption.test.ts
  frontend/__test__/hooks/useWritingOption.test.tsx
  frontend/src/components/PostForm/ContentImageSection/index.tsx
  frontend/src/components/PostForm/constants.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/PostForm/validation.ts
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/constants.ts
  frontend/src/components/common/TimePickerOptionList/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/OptionUploadImageButton.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/WritingVoteOption.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
  frontend/src/constants/policyMessage.ts
  frontend/src/constants/post.ts
  frontend/src/hooks/useWritingOption.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/types/post.ts
  frontend/src/utils/post/convertImageUrlToServerUrl.ts
  frontend/src/utils/post/deleteOverlappingNewLine.ts
  frontend/src/utils/post/formatTime.ts
  frontend/src/utils/post/getDeadlineTime.ts
  frontend/src/utils/post/getSelectedTimeOption.ts
  frontend/src/utils/time.ts
Labels: FE, 🐾 개발, 🐛 버그

#653 리프레시 토큰 명세와 다른 코드 수정
  frontend/src/api/token.ts
Labels: FE, 🐛 버그

#636 head에 description meta 추가
  frontend/public/index.html
Labels: FE, 🐾 개발

#657 리프레시 토큰 중복된 요청 보내지 않도록 하기
  frontend/src/utils/token/silentLogin.ts
Labels: FE, 🐛 버그

#641 게시글 리스트에서 CSS 다르게 보이는 문제 해결
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostList/style.ts
Labels: FE, 🐛 버그

#638 에러가 나왔을 때 헤더가 두개로 표시되는 것을 수정, 에러 바운더리에서 홈으로가기, 다시시도 버튼 추가
  frontend/src/components/common/ErrorMessage/ErrorMessage.stories.tsx
  frontend/src/components/common/ErrorMessage/index.tsx
  frontend/src/components/common/ErrorMessage/style.ts
  frontend/src/pages/ErrorBoundaryWithNarrowHeader.tsx
  frontend/src/pages/post/EditPostPage/index.tsx
  frontend/src/pages/post/PostDetail/index.tsx
Labels: FE, 🐾 개발, 🐛 버그

#662 fix: (#661) 로그아웃 시 쿠키를 보내도록 설정
  frontend/src/api/userInfo.ts
Labels: FE, 🐛 버그

#637 게시물 링크 복사 버튼 구현, 댓글 작성폼에 링크 넣기 기능 추가, 모바일 Toast 잘리는 이슈 해결
  frontend/src/assets/chain.svg
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/style.ts
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/SquareButton/style.ts
  frontend/src/components/common/Toast/style.ts
  frontend/src/pages/post/PostDetail/InnerHeaderPart/style.ts
  frontend/src/pages/post/PostDetail/PostDetail/index.tsx
  frontend/src/pages/post/PostDetail/PostDetail/style.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/post/formatTextLink.tsx
Labels: FE, 🐾 개발, 🐛 버그

#651 채널톡이 앱설치 프롬프트와 랭킹 페이지의 내랭킹을 가리는 버그 수정
  frontend/package-lock.json
  frontend/src/components/ChannelTalk/index.tsx
  frontend/src/components/common/AppInstallPrompt/BookMarkPrompt/style.ts
  frontend/src/components/common/AppInstallPrompt/index.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/pages/Ranking/index.tsx
Labels: FE, 🐛 버그

#665 불필요하게 큰 에셋 파일들 용량 줄임, 웹팩
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets.d.ts
  frontend/src/assets/comment.svg
  frontend/src/assets/first-rank.svg
  frontend/src/assets/first-rank.webp
  frontend/src/assets/kakao_login.svg
  frontend/src/assets/kakao_login.webp
  frontend/src/assets/kakao_login_large.svg
  frontend/src/assets/kakao_login_large.webp
  frontend/src/assets/kakao_login_medium_wide.svg
  frontend/src/assets/kakao_login_medium_wide.webp
  frontend/src/assets/photo_black.svg
  frontend/src/assets/ranking.png
  frontend/src/assets/ranking.svg
  frontend/src/assets/second-rank.svg
  frontend/src/assets/second-rank.webp
  frontend/src/assets/third-rank.svg
  frontend/src/assets/third-rank.webp
  frontend/src/assets/user.png
  frontend/src/assets/user.svg
  frontend/src/assets/votogether_home.png
  frontend/src/assets/votogether_home.webp
  frontend/src/assets/votogether_write.png
  frontend/src/assets/votogether_write.webp
  frontend/src/components/comment/CommentList/CommentLoginSection/index.tsx
  frontend/src/components/common/Dashboard/GuestProfile/index.tsx
  frontend/src/components/common/IconButton/index.tsx
  frontend/src/pages/Ranking/PassionUser/index.tsx
  frontend/src/pages/Ranking/PopularPost/index.tsx
  frontend/src/pages/auth/Login/MobileLogin/index.tsx
  frontend/src/pages/auth/Login/ServiceIntroductionSection/index.tsx
  frontend/webpack.analyzer.js
  frontend/webpack.common.js
Labels: FE, 🛠 리팩터링

#660 댓글 및 게시글에 대한 중복 Mutation 방지 처리, 가공된 에러 메시지를 Toast로 띄우도록 수정
  frontend/src/components/PostForm/PostForm.stories.tsx
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/ReportModal/ReportModal.stories.tsx
  frontend/src/components/ReportModal/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/common/DeleteModal/DeleteModal.stories.tsx
  frontend/src/components/common/DeleteModal/index.tsx
  frontend/src/components/common/HeaderTextButton/index.tsx
  frontend/src/components/common/HeaderTextButton/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/hooks/query/post/useDeletePost.ts
  frontend/src/pages/post/CreatePostPage/index.tsx
  frontend/src/pages/post/EditPostPage/EditPost/index.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/BottomButtonPart.stories.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/InnerHeaderPart.stories.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
  frontend/src/pages/post/PostDetail/PostDetail/index.tsx
  frontend/src/pages/post/PostDetail/types.ts
Labels: FE, 🐛 버그

#659 투표 관련 예외 메시지 변환
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/vote/exception/VoteExceptionType.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
Labels: BE, 🐛 버그

#681 Release 1.2.1
  frontend/src/assets/arrow-right.png
  frontend/src/components/comment/CommentList/CommentTextForm/style.ts
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/style.ts
  frontend/src/components/common/SquareButton/style.ts
  frontend/src/pages/Ranking/PassionUser/style.ts
  frontend/src/pages/Ranking/PopularPost/style.ts
  frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
Labels: BE, FE

#684 이미지 압축 패키지를 Browser Image Compression에서 upload-images-converter로 변경
  frontend/__test__/calculateAspectRatioSize.test.ts
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/useContentImage.ts
  frontend/src/utils/calculateAspectRatioSize.ts
  frontend/src/utils/getImageSize.ts
  frontend/src/utils/resizeImage.ts
Labels: FE, 🛠 리팩터링

#694 이벤트 상품 수령 대상자 공지
  frontend/package-lock.json
  frontend/src/constants/policyMessage.ts
  frontend/src/pages/AnnouncementPage/index.tsx
Labels: FE, 🐾 개발

#696 인기순/최신순 정렬에서 선택된 옵션이 영어로 보이는 버그 수정, 공지사항 내용 추가
  frontend/src/components/post/PostList/index.tsx
  frontend/src/pages/AnnouncementPage/index.tsx
Labels: FE, 🐛 버그
