Repository woowacourse-teams/2023-votogether, pull requests merged in 2023-07, with the labels that each got.

#2 PR 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/bug-report-버그-수정-템플릿-.md
  .github/ISSUE_TEMPLATE/feature-request-기능-개발-템플릿-.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: /(ㄒoㄒ)/~~

#5 백엔드 프로젝트 생성
  .gitignore
  backend/.gitignore
  backend/README.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/votogether/VotogetherApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/votogether/VotogetherApplicationTests.java
Labels: 👑 백앤드, 🐾 개발

#9 멤버의 Entity, Repository 구현
  backend/src/main/java/com/votogether/domain/member/entity/Gender.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/MemberCategory.java
  backend/src/main/java/com/votogether/domain/member/entity/SocialType.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/votogether/domain/vote/entity/Vote.java
Labels: 👑 백엔드, 🐾 개발

#10 게시글의 Entity, Repository 구현
  backend/src/main/java/com/votogether/domain/category/entity/Category.java
  backend/src/main/java/com/votogether/domain/category/repository/CategoryRepository.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostCategory.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/domain/post/repository/PostRepository.java
Labels: 👑 백엔드, 🐾 개발

#11 프론트엔드 프로젝트 설정
  .vscode/settings.json
  frontend/.babelrc.json
  frontend/.eslintrc
  frontend/.gitignore
  frontend/.prettierrc.js
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/__test__/hook.test.tsx
  frontend/__test__/unit.test.js
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/Button/style.ts
  frontend/src/hooks/useCount.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/styles/globalStyle.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🦄 프론트, 🐾 개발

#13 전체 Entity 연관관계 매핑, Auditing 기능 추가
  backend/src/main/java/com/votogether/domain/category/entity/Category.java
  backend/src/main/java/com/votogether/domain/common/BaseEntity.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/MemberCategory.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostCategory.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/domain/vote/entity/Vote.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: 👑 백엔드, 🐾 개발

#27 Jpa Auditing, Swagger 설정
  backend/build.gradle
  backend/src/main/java/com/votogether/VotogetherApplication.java
  backend/src/main/java/com/votogether/config/JpaConfig.java
  backend/src/main/java/com/votogether/config/OpenAPIConfig.java
  backend/src/main/java/com/votogether/domain/common/BaseEntity.java
  backend/src/main/java/com/votogether/domain/healthcheck/controller/HealthCheckController.java
  backend/src/main/java/com/votogether/domain/healthcheck/service/HealthCheckService.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/VotogetherApplicationTests.java
Labels: 👑 백엔드, 🐾 개발

#28 공통 모달 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/Modal/style.ts
Labels: 🦄 프론트, 🐾 개발

#31 공통 버튼 컴포넌트 구현
  frontend/package-lock.json
  frontend/src/assets/back.svg
  frontend/src/assets/category.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/projectName.svg
  frontend/src/assets/search.svg
  frontend/src/components/common/AddButton/AddButton.stories.tsx
  frontend/src/components/common/AddButton/index.tsx
  frontend/src/components/common/AddButton/style.ts
  frontend/src/components/common/AddButton/type.ts
  frontend/src/components/common/HeaderTextButton/HeaderTextButton.stories.tsx
  frontend/src/components/common/HeaderTextButton/index.tsx
  frontend/src/components/common/HeaderTextButton/style.ts
  frontend/src/components/common/IconButton/IconButton.stories.tsx
  frontend/src/components/common/IconButton/index.tsx
  frontend/src/components/common/IconButton/style.ts
  frontend/src/components/common/SquareButton/SquareButton.stories.tsx
  frontend/src/components/common/SquareButton/index.tsx
  frontend/src/components/common/SquareButton/style.ts
  frontend/src/svg.d.ts
  frontend/tsconfig.json
Labels: 🦄 프론트, 🐾 개발

#37 PR 진행 시 테스트 통과 선행 기능 구현
  .github/workflows/backend-pr-test.yml
  .gitignore
Labels: 🐾 개발, 🐳 인프라

#35 TimePickerOption, TimePickerOptionList 컴포넌트 구현
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/TimePickerOption.stories.tsx
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/constants.ts
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/index.tsx
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/style.ts
  frontend/src/components/common/TimePickerOptionList/TimePickerOptionList.stories.tsx
  frontend/src/components/common/TimePickerOptionList/index.tsx
  frontend/src/components/common/TimePickerOptionList/style.ts
Labels: 🦄 프론트, 🐾 개발

#39 헤더 컴포넌트 구현_Feat/#16
  frontend/src/assets/search_black.svg
  frontend/src/assets/search_white.svg
  frontend/src/components/common/AddButton/AddButton.stories.tsx
  frontend/src/components/common/HeaderTextButton/HeaderTextButton.stories.tsx
  frontend/src/components/common/IconButton/IconButton.stories.tsx
  frontend/src/components/common/IconButton/index.tsx
  frontend/src/components/common/LogoButton/LogoButton.stories.tsx
  frontend/src/components/common/LogoButton/index.tsx
  frontend/src/components/common/LogoButton/style.ts
  frontend/src/components/common/NarrowMainHeader/NarrowMainHeader.stories.tsx
  frontend/src/components/common/NarrowMainHeader/index.tsx
  frontend/src/components/common/NarrowMainHeader/style.ts
  frontend/src/components/common/NarrowTemplateHeader/NarrowTemplateHeader.stories.tsx
  frontend/src/components/common/NarrowTemplateHeader/index.tsx
  frontend/src/components/common/NarrowTemplateHeader/style.ts
  frontend/src/components/common/SearchBar/SearchBar.stories.tsx
  frontend/src/components/common/SearchBar/index.tsx
  frontend/src/components/common/SearchBar/style.ts
  frontend/src/components/common/SquareButton/SquareButton.stories.tsx
  frontend/src/components/common/WideHeader/WideHeader.stories.tsx
  frontend/src/components/common/WideHeader/index.tsx
  frontend/src/components/common/WideHeader/style.ts
Labels: 🦄 프론트, 🐾 개발

#48 리액트 쿼리, msw 설치 및 셋팅
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/.storybook/public/mockServiceWorker.js
  frontend/.storybook/webpack.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/mocks/example/get.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/worker.ts
  frontend/webpack.common.js
Labels: 🦄 프론트, 🐾 개발

#40 투표 작성 페이지의 투표 선택지 컴포넌트 UI 구현
  frontend/__test__/hooks/useWritingOption.test.tsx
  frontend/src/assets/photo_white.svg
  frontend/src/assets/x_mark_white.svg
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionCancelButton/OptionCancelButton.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionCancelButton/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionCancelButton/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/OptionUploadImageButton.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/WritingVoteOption.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOptionList.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/style.ts
  frontend/src/hooks/useWritingOption.tsx
Labels: 🦄 프론트, 🐾 개발

#42 공통 스타일링 속성 관리 및 페이지 라우팅 설정
  frontend/.storybook/preview.tsx
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Example/style.ts
  frontend/src/constants/path.ts
  frontend/src/pages/Post/PostDetail.tsx
  frontend/src/pages/Post/PostList.tsx
  frontend/src/pages/Post/WritePost.tsx
  frontend/src/pages/post/PostDetail.tsx
  frontend/src/pages/post/PostList.tsx
  frontend/src/pages/post/WritePost.tsx
  frontend/src/routes/router.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
  frontend/webpack.common.js
Labels: 🦄 프론트, 🐾 개발

#53 작성된 게시글 컴포넌트 구현_Feat/#24
  frontend/.storybook/preview.tsx
  frontend/src/CONSTATNS/index.ts
  frontend/src/api/sua/post.ts
  frontend/src/components/common/Post/Post.stories.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/mockData.ts
  frontend/src/components/common/Post/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/sua/vote.ts
  frontend/src/types/post.ts
Labels: 🦄 프론트, 🐾 개발

#45 TimePicker Modal 구현
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/TimePickerOption.stories.tsx
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/constants.ts
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/index.tsx
  frontend/src/components/common/TimePickerOptionList/TimePickerOptionList.stories.tsx
  frontend/src/components/common/TimePickerOptionList/index.tsx
  frontend/src/components/common/TimePickerOptionList/style.ts
Labels: 🦄 프론트, 🐾 개발

#60 스켈레톤 UI 구현
  frontend/src/components/common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/common/Skeleton/index.tsx
  frontend/src/components/common/Skeleton/style.ts
Labels: 🦄 프론트, 🐾 개발

#56 투표 상세 통계 컴포넌트 제작_#54
  frontend/src/components/Example/style.ts
  frontend/src/components/VoteStatistics/GraphStyle.ts
  frontend/src/components/VoteStatistics/OneLineGraph/OneLineGraph.stories.tsx
  frontend/src/components/VoteStatistics/OneLineGraph/index.tsx
  frontend/src/components/VoteStatistics/OneLineGraph/style.ts
  frontend/src/components/VoteStatistics/TwoLineGraph/TwoLineGraph.stories.tsx
  frontend/src/components/VoteStatistics/TwoLineGraph/index.tsx
  frontend/src/components/VoteStatistics/TwoLineGraph/style.ts
  frontend/src/components/VoteStatistics/VoteStatistics.stories.tsx
  frontend/src/components/VoteStatistics/index.tsx
  frontend/src/components/VoteStatistics/mockData.ts
  frontend/src/components/VoteStatistics/style.ts
  frontend/src/components/VoteStatistics/type.ts
  frontend/src/components/common/Post/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/style.ts
Labels: 🦄 프론트, 🐾 개발

#57 사이드바(Drawer) 컴포넌트 UI 구현
  frontend/src/assets/chevron-down.svg
  frontend/src/assets/chevron-up.svg
  frontend/src/assets/kakao_login.svg
  frontend/src/components/common/Dashboard/CategoryToggle/CategoryToggle.stories.tsx
  frontend/src/components/common/Dashboard/CategoryToggle/index.tsx
  frontend/src/components/common/Dashboard/CategoryToggle/style.ts
  frontend/src/components/common/Dashboard/Dashboard.stories.tsx
  frontend/src/components/common/Dashboard/GuestProfile/GuestProfile.stories.tsx
  frontend/src/components/common/Dashboard/GuestProfile/index.tsx
  frontend/src/components/common/Dashboard/GuestProfile/style.ts
  frontend/src/components/common/Dashboard/UserProfile/UserProfile.stories.tsx
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/style.ts
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/components/common/Dashboard/profileStyle.ts
  frontend/src/components/common/Dashboard/style.ts
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/Drawer/index.tsx
  frontend/src/components/common/Drawer/style.ts
  frontend/src/components/common/NarrowMainHeader/NarrowMainHeader.stories.tsx
  frontend/src/components/common/NarrowMainHeader/index.tsx
  frontend/src/hooks/useDrawer.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/types/category.ts
  frontend/src/types/user.ts
Labels: 🦄 프론트, 🐾 개발

#47 게시글 선택지 투표기능, 투표 수정기능 구현
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/repository/PostOptionRepository.java
  backend/src/main/java/com/votogether/domain/vote/controller/VoteController.java
  backend/src/main/java/com/votogether/domain/vote/entity/Vote.java
  backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
Labels: 👑 백엔드, 🐾 개발

#52 (비회원) 전체 카테고리 목록 조회 API 구현
  backend/src/main/java/com/votogether/domain/category/contorller/CategoryController.java
  backend/src/main/java/com/votogether/domain/category/dto/response/CategoryResponse.java
  backend/src/main/java/com/votogether/domain/category/entity/Category.java
  backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
  backend/src/test/java/com/votogether/domain/RepositoryTest.java
  backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
Labels: 👑 백엔드, 🐾 개발

#73 jest 환경 설정(절대 경로, jest 환경 fetch) 및 배포 되도록 에러 코드 수정
  frontend/.eslintrc
  frontend/.gitignore
  frontend/__test__/hook.test.tsx
  frontend/__test__/hooks/useWritingOption.test.tsx
  frontend/jest.config.js
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/OptionUploadImageButton.stories.tsx
  frontend/src/routes/router.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🦄 프론트, 🐾 개발

#69 게시글 작성 기능 구현
  backend/build.gradle
  backend/src/main/java/com/votogether/config/SwaggerBeanConfig.java
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/dto/request/PostCreateRequest.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostBody.java
  backend/src/main/java/com/votogether/domain/post/entity/PostCategories.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOptions.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerIntegratedTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostCategoriesTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostOptionsTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/integrated/IntegrationTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
  backend/src/test/resources/images/testImage1.PNG
  backend/src/test/resources/images/testImage2.PNG
Labels: 👑 백엔드, 🐾 개발

#70 (회원) 선호 카테고리 추가 기능 구현
  backend/src/main/java/com/votogether/domain/category/contorller/CategoryController.java
  backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberCategoryRepository.java
  backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
Labels: 👑 백엔드, 🐾 개발

#58 공용 Select 컴포넌트 UI 구현
  frontend/src/components/common/Select/Select.stories.tsx
  frontend/src/components/common/Select/constants.ts
  frontend/src/components/common/Select/index.tsx
  frontend/src/components/common/Select/style.ts
  frontend/src/styles/globalStyle.ts
Labels: 🦄 프론트, 🐾 개발

#75 게시글 통계 컴포넌트 제작_Feat/#65
  frontend/src/api/sua/post.ts
  frontend/src/api/sua/voteResult.ts
  frontend/src/components/VoteStatistics/OneLineGraph/index.tsx
  frontend/src/components/VoteStatistics/TwoLineGraph/index.tsx
  frontend/src/components/VoteStatistics/index.tsx
  frontend/src/components/common/LoadingSpinner/LoadingSpinner.stories.tsx
  frontend/src/components/common/LoadingSpinner/index.tsx
  frontend/src/components/common/LoadingSpinner/style.ts
  frontend/src/components/common/NarrowMainHeader/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/hooks/useFetch.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/mockData/voteDetail.json
  frontend/src/mocks/sua/getVoteDetail.ts
  frontend/src/pages/VoteStatistics/OptionStatistics/OptionStatistics.stories.tsx
  frontend/src/pages/VoteStatistics/OptionStatistics/index.tsx
  frontend/src/pages/VoteStatistics/OptionStatistics/style.ts
  frontend/src/pages/VoteStatistics/VoteStatistics.stories.tsx
  frontend/src/pages/VoteStatistics/index.tsx
  frontend/src/pages/VoteStatistics/style.ts
Labels: 🦄 프론트, 🐾 개발

#72 글 작성 및 수정 페이지 구현
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/api/jero/post.ts
  frontend/src/components/PostForm/PostForm.stories.tsx
  frontend/src/components/PostForm/constants.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/OptionUploadImageButton.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/query/post/useCreatePost.ts
  frontend/src/hooks/query/post/useEditPost.ts
  frontend/src/hooks/useText.ts
  frontend/src/hooks/useToggle.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/jero/post.ts
  frontend/src/pages/post/CreatePost/index.tsx
  frontend/src/pages/post/EditPost/index.tsx
  frontend/src/pages/post/WritePost.tsx
  frontend/src/routes/router.tsx
  frontend/src/utils/fetch.ts
  frontend/src/utils/post/formatTime.ts
Labels: 🦄 프론트, 🐾 개발

#79 (회원) 선호 카테고리 삭제 기능 구현
  backend/src/main/java/com/votogether/domain/category/contorller/CategoryController.java
  backend/src/main/java/com/votogether/domain/category/dto/response/CategoryResponse.java
  backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberCategoryRepository.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
  backend/src/test/java/com/votogether/domain/category/contorller/CategoryControllerTest.java
  backend/src/test/java/com/votogether/domain/category/service/CategoryServiceTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
Labels: BE, 🐾 개발

#83 선택지 통계 조회 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/votogether/config/SwaggerBeanConfig.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/dto/request/PostCreateRequest.java
  backend/src/main/java/com/votogether/domain/post/dto/response/VoteCountForAgeGroupResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/VoteOptionStatisticsResponse.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/domain/vote/dto/VoteStatus.java
  backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
  backend/src/main/java/com/votogether/exception/BadRequestException.java
  backend/src/main/java/com/votogether/exception/BaseException.java
  backend/src/main/java/com/votogether/exception/ExceptionResponse.java
  backend/src/main/java/com/votogether/exception/ExceptionType.java
  backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/votogether/exception/NotFoundException.java
  backend/src/test/java/com/votogether/RepositoryTest.java
  backend/src/test/java/com/votogether/ServiceTest.java
  backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/category/service/CategoryServiceTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
  backend/src/test/java/com/votogether/fixtures/CategoryFixtures.java
  backend/src/test/java/com/votogether/fixtures/MemberFixtures.java
Labels: BE, 🐾 개발

#82 회원가입 및 로그인 & 인가 기능 구현
  backend/build.gradle
  backend/src/main/java/com/votogether/VotogetherApplication.java
  backend/src/main/java/com/votogether/config/JpaConfig.java
  backend/src/main/java/com/votogether/config/WebMvcConfig.java
  backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
  backend/src/main/java/com/votogether/domain/auth/dto/KakaoMemberResponse.java
  backend/src/main/java/com/votogether/domain/auth/dto/LoginResponse.java
  backend/src/main/java/com/votogether/domain/auth/dto/OAuthAccessTokenResponse.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/NicknameNumberGenerator.java
  backend/src/main/java/com/votogether/domain/member/entity/NumberGenerator.java
  backend/src/main/java/com/votogether/domain/member/entity/SocialType.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/global/jwt/Auth.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthorizationArgumentResolver.java
  backend/src/main/java/com/votogether/global/jwt/TokenPayload.java
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/votogether/domain/category/contorller/CategoryControllerTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerIntegratedTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
  backend/src/test/java/com/votogether/fixtures/MemberFixtures.java
  backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🐾 개발

#89 (회원) 전체 카테고리 목록 조회 기능 구현
  backend/src/main/java/com/votogether/domain/category/contorller/CategoryController.java
  backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
  backend/src/test/java/com/votogether/domain/category/contorller/CategoryControllerTest.java
Labels: BE, 🐾 개발

#98 로그 기능 추가
  backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
Labels: BE, 🐾 개발

#101 CORS Origin 설정
  backend/src/main/java/com/votogether/config/WebMvcConfig.java
Labels: BE, 🛠 리팩터링

#87 레이아웃 컴포넌트 구현
  frontend/src/components/common/Dashboard/style.ts
  frontend/src/components/common/Layout/Layout.stories.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Layout/style.ts
Labels: FE, 🐾 개발

#84 게시글 상세페이지 컴포넌트_Feat/#78
  frontend/src/components/common/HeaderTextButton/style.ts
  frontend/src/components/common/TagButton/TagButton.stories.tsx
  frontend/src/components/common/TagButton/index.tsx
  frontend/src/components/common/TagButton/style.ts
  frontend/src/constants/post.ts
  frontend/src/hooks/useFetch_2.ts
  frontend/src/mocks/sua/post.ts
  frontend/src/pages/post/PostDetail.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/BottomButtonPart.stories.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/style.ts
  frontend/src/pages/post/PostDetail/InnerHeaderPart/InnerHeaderPart.stories.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/style.ts
  frontend/src/pages/post/PostDetail/PostDetail.stories.tsx
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/pages/post/PostDetail/style.ts
  frontend/src/routes/router.tsx
  frontend/src/utils/time.ts
Labels: FE, 🐾 개발

#85 홈페이지에서 사용할 전체 게시글 리스트 컴포넌트 구현
  frontend/__test__/api/postList.test.ts
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/__test__/hooks/useSelect.test.tsx
  frontend/src/api/wus/postList.ts
  frontend/src/assets/chevron_up_primary.svg
  frontend/src/components/common/Drawer/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/components/common/Select/index.tsx
  frontend/src/components/common/Select/style.ts
  frontend/src/components/common/UpButton/UpButton.stories.tsx
  frontend/src/components/common/UpButton/index.tsx
  frontend/src/components/common/UpButton/style.ts
  frontend/src/components/post/PostList/PostList.stories.tsx
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostList/style.ts
  frontend/src/components/post/PostListPage/PostListPage.stories.tsx
  frontend/src/components/post/PostListPage/constants.ts
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/components/post/PostListPage/style.ts
  frontend/src/components/post/PostListPage/types.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/hooks/useIntersectionObserver.tsx
  frontend/src/hooks/useSelect.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/mockData/category.ts
  frontend/src/mocks/mockData/postList.ts
  frontend/src/mocks/mockData/user.ts
  frontend/src/mocks/wus/post.ts
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
  frontend/src/types/post.ts
Labels: FE, 🐾 개발

#117 배포를 위해 현재 발생한 오류 해결 및 페이지 생성_Feat/#106
  frontend/__test__/api/postList.test.ts
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/__test__/hooks/useSelect.test.tsx
  frontend/src/api/post.ts
  frontend/src/api/wus/postList.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/common/Layout/Layout.stories.tsx
  frontend/src/components/common/Modal/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/mockData.ts
  frontend/src/components/common/Post/style.ts
  frontend/src/components/common/TagButton/index.tsx
  frontend/src/components/common/TagButton/style.ts
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/constants/post.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/sua/post.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
  frontend/src/pages/VoteStatistics/index.tsx
  frontend/src/pages/post/CreatePost/index.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/style.ts
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/routes/router.tsx
  frontend/src/styles/theme.ts
  frontend/styled-components.d.ts
Labels: FE, 🛠 리팩터링, 🐾 개발

#90 카테고리 정보를 불러오는 패치 api 함수 구현 및 msw mocking 구현
  frontend/__test__/api/categoryList.test.ts
  frontend/src/api/wus/categoryList.ts
  frontend/src/mocks/mockData/categoryList.ts
  frontend/src/mocks/wus/categoryList.ts
  frontend/src/types/category.ts
Labels: FE, 🐾 개발

#107 유저 정보를 불러오는 패치 api 함수 구현 및 msw mocking 구현
  frontend/__test__/api/user.test.ts
  frontend/src/api/wus/userInfo.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/mockData/user.ts
  frontend/src/mocks/wus/userInfo.ts
  frontend/src/types/user.ts
Labels: FE, 🐾 개발

#122 카카오에 엑세스 토큰 요청 시 타입 설정 및 회원 닉네임 반환 오류 수정
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
Labels: BE, 🛠 리팩터링

#112 전체 통계 조회 기능 구현
  backend/src/main/java/com/votogether/domain/category/contorller/CategoryController.java
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/dto/response/VoteOptionStatisticsResponse.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/domain/vote/controller/VoteController.java
  backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
  backend/src/test/java/com/votogether/domain/category/contorller/CategoryControllerTest.java
  backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/category/service/CategoryServiceTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerIntegratedTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostCategoriesTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostOptionsTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
  backend/src/test/java/com/votogether/fixtures/CategoryFixtures.java
  backend/src/test/java/com/votogether/fixtures/MemberFixtures.java
Labels: BE, 🐾 개발

#113 카테고리별 게시글 조회 기능을 위해 getPostList 함수 수정 이후 usePostList 훅 추가 기능 구현
  frontend/__test__/api/postList.test.ts
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/src/api/wus/postList.ts
  frontend/src/components/post/PostList/constants.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/wus/post.ts
  frontend/src/routes/router.tsx
Labels: FE, 🐾 개발

#132 통계페이지 등 전체 스타일 수정하기_Feat/#123
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/assets/search_black.svg
  frontend/src/components/PostForm/style.ts
  frontend/src/components/common/Drawer/style.ts
  frontend/src/components/common/Layout/Layout.stories.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Layout/style.ts
  frontend/src/components/common/NarrowMainHeader/style.ts
  frontend/src/components/common/NarrowTemplateHeader/style.ts
  frontend/src/components/common/Post/style.ts
  frontend/src/components/common/WideHeader/WideHeader.stories.tsx
  frontend/src/components/common/WideHeader/index.tsx
  frontend/src/components/common/WideHeader/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
  frontend/src/components/post/PostListPage/PostListPage.stories.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useFetch_2.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
  frontend/src/pages/VoteStatistics/index.tsx
  frontend/src/pages/VoteStatistics/style.ts
  frontend/src/pages/post/CreatePost/index.tsx
  frontend/src/pages/post/EditPost/index.tsx
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/pages/post/PostDetail/style.ts
  frontend/src/pages/post/PostList.tsx
Labels: FE, 🐾 개발

#135 webpack prod에서 .env를 사용하도록 수정 & jest에서 .env 파일 인식하도록 설정
  frontend/.env.test
  frontend/package.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
Labels: FE, 🐾 개발, 🐳 인프라

#133 .env 파일 타입 선언 및 router 및 경로 설정
  frontend/env.d.ts
  frontend/src/components/common/Dashboard/CategoryToggle/index.tsx
  frontend/src/components/common/Dashboard/CategoryToggle/style.ts
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/constants/path.ts
  frontend/src/routes/router.tsx
  frontend/tsconfig.json
Labels: FE, 🛠 리팩터링, 🐾 개발

#142 Swagger 페이지에 정상적으로 접근할 수 없는 오류
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
Labels: BE, 🐛 버그

#144 Swagger 디폴트페이지 버그 해결
  backend/src/main/resources/application.yml
Labels: BE, 🐛 버그

#147 게시글 수정 api 변경에 따른 적용_Feat/#145
  frontend/src/components/PostForm/index.tsx
Labels: FE, 🐾 개발

#140 웹 화면에서 글 게시글 작성 저장 버튼이 보이도록 수정 및 스타일 수정
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/style.ts
  frontend/src/components/optionList/WritingVoteOptionList/style.ts
Labels: FE, 🛠 리팩터링, 🐾 개발

#148 내가 작성한 게시글 조회, 내가 투표한 게시글 조회 기능 구현
  frontend/__test__/api/postList.test.ts
  frontend/__test__/getPathFragment.test.ts
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/jest.setup.js
  frontend/package.json
  frontend/src/api/postList.ts
  frontend/src/api/wus/postList.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostListPage/constants.ts
  frontend/src/components/post/PostListPage/types.ts
  frontend/src/constants/path.ts
  frontend/src/constants/post.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/hooks/usePostRequestInfo.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/mockData/postList.ts
  frontend/src/mocks/wus/post.ts
  frontend/src/types/post.ts
  frontend/src/utils/getPathFragment.ts
Labels: FE, 🐾 개발

#150 husky 설치, git commit/push 전 lint 오류 검사 자동화
  frontend/.husky/pre-commit
  frontend/.husky/pre-push
  frontend/package-lock.json
  frontend/package.json
  frontend/src/mocks/example/get.ts
Labels: FE, 🐾 개발

#159 닉네임 수정 기능 구현
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
  backend/src/main/java/com/votogether/domain/member/dto/MemberNicknameUpdateRequest.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/Nickname.java
  backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
  backend/src/main/java/com/votogether/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
Labels: BE, 🐾 개발

#151 댓글 작성 기능 구현
  backend/src/main/java/com/votogether/config/OpenAPIConfig.java
  backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
  backend/src/main/java/com/votogether/domain/post/dto/request/CommentRegisterRequest.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/comment/Comment.java
  backend/src/main/java/com/votogether/domain/post/entity/comment/Content.java
  backend/src/main/java/com/votogether/domain/post/exception/CommentExceptionType.java
  backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/main/java/com/votogether/exception/ExceptionResponse.java
  backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/votogether/global/jwt/Auth.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/comment/CommentTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostCommentServiceTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🐾 개발

#162 회원 탈퇴 기능 구현
  backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
Labels: BE, 🐾 개발

#161 댓글 삭제 기능 구현
  backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
  backend/src/main/java/com/votogether/domain/post/entity/comment/Comment.java
  backend/src/main/java/com/votogether/domain/post/exception/CommentExceptionType.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/entity/comment/CommentTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostCommentServiceTest.java
Labels: BE, 🐾 개발

#160 글 작성/수정 시 본문에 사진 추가/삭제 기능 구현_Feat/#155
  frontend/src/components/PostForm/ContentImageSection/index.tsx
  frontend/src/components/PostForm/ContentImageSection/style.ts
  frontend/src/components/PostForm/PostForm.stories.tsx
  frontend/src/components/PostForm/constants.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/common/Post/mockData.ts
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/WritingVoteOption.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOptionList.stories.tsx
  frontend/src/components/optionList/WritingVoteOptionList/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/WrittenVoteOption.stories.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOptionList.stories.tsx
  frontend/src/hooks/useContentImage.ts
  frontend/src/hooks/useWritingOption.tsx
  frontend/src/mocks/mockData/postList.ts
  frontend/src/mocks/sua/post.ts
  frontend/src/pages/post/EditPost/index.tsx
  frontend/src/types/post.ts
Labels: FE, 🐾 개발

#146 다중 선택 컴포넌트 구현
  frontend/src/components/common/MultiSelect/MultiSelect.stories.tsx
  frontend/src/components/common/MultiSelect/index.tsx
  frontend/src/components/common/MultiSelect/style.ts
  frontend/src/components/common/MultiSelect/types.ts
  frontend/src/hooks/useMultiSelect.ts
Labels: FE, 🐾 개발

#171 댓글 수정 기능 구현
  backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
  backend/src/main/java/com/votogether/domain/post/dto/request/CommentUpdateRequest.java
  backend/src/main/java/com/votogether/domain/post/entity/comment/Comment.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/comment/CommentTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostCommentServiceTest.java
Labels: BE, 🐾 개발

#156 카테고리 목록 조회, 카테고리 즐겨찾기, 유저 정보 조회에 대한 커스텀 쿼리 구현
  frontend/src/components/common/Dashboard/CategoryToggle/CategoryToggle.stories.tsx
  frontend/src/components/common/Dashboard/CategoryToggle/index.tsx
  frontend/src/components/common/Dashboard/Dashboard.stories.tsx
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/query/category/useCategoryFavoriteToggle.ts
  frontend/src/hooks/query/category/useCategoryList.ts
  frontend/src/hooks/query/user/useUserInfo.ts
  frontend/src/mocks/wus/categoryList.ts
  frontend/src/utils/fetch.ts
Labels: FE, 🐾 개발

#166 스토리북을 PR이 merge 될 때 배포되도록 설정
  .github/workflows/frontend-storybook-deploy.yml
Labels: FE, 🐳 인프라
