Repository woowacourse-teams/2023-votogether, pull requests merged in 2023-11, with the labels that each got.

#835 인기순 전체 게시글 목록 조회 기능의 성능 개선을 위한 QueryDsl 코드 수정
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
Labels: BE, 🛠 리팩터링

#834 단위 테스트(jest 테스트) 실행 시간 최적화
  frontend/.env.test
  frontend/.gitignore
  frontend/.husky/pre-push
  frontend/__test__/hooks/usePagination.test.tsx
  frontend/jest.config.js
  frontend/package.json
  frontend/src/mocks/alarm.ts
  frontend/src/mocks/comment.ts
  frontend/src/mocks/getVoteDetail.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/notice.ts
  frontend/src/mocks/post.ts
  frontend/src/mocks/postList.ts
  frontend/src/mocks/ranking.ts
  frontend/src/mocks/report.ts
  frontend/src/mocks/reportApproveResult.ts
  frontend/src/mocks/token.ts
  frontend/src/mocks/userInfo.ts
  frontend/src/mocks/vote.ts
Labels: FE, 👷🏻 테스트

#838 글 작성/수정 폼 리팩토링해서 폼 훅 분리하기
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/type.ts
  frontend/src/components/PostForm/validation.ts
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/index.tsx
  frontend/src/components/common/TimePickerOptionList/TimePickerOptionList.stories.tsx
  frontend/src/components/common/TimePickerOptionList/index.tsx
  frontend/src/constants/policyMessage.ts
  frontend/src/hooks/useDeadline.tsx
  frontend/src/types/modalButton.ts
  frontend/src/utils/post/calculateDeadlineDHMTime.ts
  frontend/src/utils/post/convertToFormdata.ts
Labels: FE, 🐾 개발, 🐛 버그

#840 홈 화면 서스펜스 범위 재지정 및 셀렉트 컴포넌트 리팩터링
  frontend/src/api/userInfo.ts
  frontend/src/components/ReportModal/index.tsx
  frontend/src/components/common/Select/Select.stories.tsx
  frontend/src/components/common/Select/index.tsx
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostList/style.ts
  frontend/src/components/post/PostListFetcher/index.tsx
  frontend/src/components/post/PostListFetcher/style.ts
  frontend/src/hooks/useSelect.tsx
  frontend/src/mocks/userInfo.ts
  frontend/src/pages/HomePage/index.tsx
Labels: FE, 🐾 개발

#828 동시 로그인 시 같은 인가코드가 사용되는 문제 해결 및 카카오 회원 탈퇴 기능 보완
  backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
  backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
  backend/src/main/java/com/votogether/domain/auth/dto/response/OAuthDisconnectResponse.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
  backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthLoginInfo.java
  backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
  backend/src/main/java/com/votogether/domain/member/controller/MemberControllerDocs.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🐾 개발, 🐛 버그

#841 사이드바에 토스트가 가려지던 문제 해결 (feat.createPortal)
  frontend/public/index.html
  frontend/src/components/ToastContainer/style.ts
  frontend/src/components/common/Drawer/DrawerToastWrapper/index.tsx
  frontend/src/components/common/Drawer/DrawerToastWrapper/style.ts
  frontend/src/components/common/Drawer/index.tsx
  frontend/src/hooks/context/toast.tsx
  frontend/src/hooks/query/alarm/useReadAlarm.ts
  frontend/src/hooks/query/report/useReportAction.ts
  frontend/src/hooks/query/report/useReportContent.ts
  frontend/src/hooks/query/useReportApproveResult.tsx
  frontend/src/hooks/query/user/useReadLatestAlarm.ts
  frontend/src/hooks/query/user/useUpdateUserInfo.ts
  frontend/src/hooks/query/user/useWithdrawalMembership.ts
  frontend/src/hooks/useDrawer.tsx
  frontend/src/pages/HomePage/index.tsx
  frontend/src/types/toast.ts
Labels: FE, 🐾 개발, 🐛 버그

#844 [BUG] formData 훅 리팩토링하며 이름 미적용된 부분이 있어 오류발생
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/comment/CommentList/CommentItem/style.ts
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/style.ts
  frontend/src/components/common/Banner/style.ts
  frontend/src/components/common/Dashboard/CategorySection/index.tsx
  frontend/src/components/common/Select/style.ts
  frontend/src/components/notice/NoticeDetailFetcher/index.tsx
  frontend/src/hooks/context/postOption.tsx
  frontend/src/hooks/query/notice/useNoticeDetail.tsx
  frontend/src/hooks/query/post/usePostDetail.ts
  frontend/src/pages/ErrorBoundary.tsx
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/HomePage/style.ts
  frontend/src/pages/ReportAlarmPage/ReportApproveResult/index.tsx
  frontend/src/pages/ReportAlarmPage/index.tsx
  frontend/src/pages/notice/NoticeDetailPage/index.tsx
  frontend/src/pages/post/CreatePostPage/index.tsx
  frontend/src/pages/post/EditPostPage/EditPost/index.tsx
  frontend/src/pages/post/PostDetailPage/PostDetail/index.tsx
  frontend/src/pages/post/PostDetailPage/index.tsx
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/post/convertToFormData.ts
  frontend/src/utils/post/getSelectedPostListState.ts
Labels: FE, 🐛 버그
