Repository woowacourse-teams/2023-votogether, pull requests merged in 2023-08, with the labels that each got.

#170 댓글 등록, 조회, 수정, 삭제 API fetch 함수 구현 및 커스텀 쿼리 구현
  frontend/src/api/comment.ts
  frontend/src/components/common/TimePickerOptionList/TimePickerOption/index.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/query/comment/useCommentList.ts
  frontend/src/hooks/query/comment/useCreateComment.ts
  frontend/src/hooks/query/comment/useDeleteComment.ts
  frontend/src/hooks/query/comment/useEditComment.ts
  frontend/src/mocks/comment.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/mockData/comment.ts
  frontend/src/types/comment.ts
Labels: FE, 🐾 개발

#178 회원 닉네임 수정, 회원 탈퇴 fetch 함수 구현 및 MSW 코드 작성
  frontend/__test__/api/user.test.ts
  frontend/src/api/wus/userInfo.ts
  frontend/src/mocks/wus/userInfo.ts
  frontend/src/types/user.ts
  frontend/src/utils/fetch.ts
Labels: FE, 🐾 개발

#182 댓글 조회 기능 구현
  backend/src/main/java/com/votogether/config/WebMvcConfig.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
  backend/src/main/java/com/votogether/domain/post/dto/response/CommentResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
  backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
  backend/src/test/java/com/votogether/domain/post/repository/CommentRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostCommentServiceTest.java
Labels: BE, 🐾 개발

#163 댓글 작성 폼, 리스트 UI 컴포넌트 구현, 댓글 타입 선언
  frontend/__test__/api/commentList.test.ts
  frontend/__test__/hooks/useMoreComment.test.tsx
  frontend/src/api/comment.ts
  frontend/src/assets/ellipsis-horizontal.svg
  frontend/src/assets/kakao_login_large.svg
  frontend/src/components/comment/CommentDeleteModal/CommentDeleteModal.stories.tsx
  frontend/src/components/comment/CommentDeleteModal/index.tsx
  frontend/src/components/comment/CommentDeleteModal/style.ts
  frontend/src/components/comment/CommentList/CommentItem/CommentItem.stories.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/CommentMenu.stories.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/style.ts
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/style.ts
  frontend/src/components/comment/CommentList/CommentList.stories.tsx
  frontend/src/components/comment/CommentList/CommentLoginSection/CommentLoginSection.stories.tsx
  frontend/src/components/comment/CommentList/CommentLoginSection/index.tsx
  frontend/src/components/comment/CommentList/CommentLoginSection/style.ts
  frontend/src/components/comment/CommentList/CommentTextForm/CommentTextForm.stories.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/style.ts
  frontend/src/components/comment/CommentList/constants.ts
  frontend/src/components/comment/CommentList/index.tsx
  frontend/src/components/comment/CommentList/style.ts
  frontend/src/components/comment/CommentList/types.ts
  frontend/src/components/comment/CommentModal/index.tsx
  frontend/src/components/comment/CommentModal/style.ts
  frontend/src/components/common/SquareButton/SquareButton.stories.tsx
  frontend/src/components/common/SquareButton/index.tsx
  frontend/src/components/common/SquareButton/style.ts
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/components/report/CommentReportModal/CommentReportModal.stories.tsx
  frontend/src/components/report/CommentReportModal/constants.ts
  frontend/src/components/report/CommentReportModal/index.tsx
  frontend/src/components/report/CommentReportModal/types.ts
  frontend/src/components/report/UserReportModal/UserReportModal.stories.tsx
  frontend/src/components/report/UserReportModal/constants.ts
  frontend/src/components/report/UserReportModal/index.tsx
  frontend/src/components/report/UserReportModal/types.ts
  frontend/src/constants/comment.ts
  frontend/src/hooks/useMoreComment.ts
  frontend/src/hooks/useToggle.tsx
  frontend/src/mocks/mockData/comment.ts
  frontend/src/types/comment.ts
  frontend/src/utils/scrollToTop.ts
Labels: FE, 🐾 개발

#115 게시글 조기 마감 기능 구현
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/integrated/IntegrationTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#191 undefined 이미지 파일 디버깅을 위해 예외 스택 호출 코드 추가
  backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
Labels: BE, 🐛 버그

#177 전체 게시글 목록 기능에 검색한 게시글 목록 기능 추가 구현 + 검색 기능 구현 + 스토리북 .env 설정
  frontend/.storybook/main.ts
  frontend/__test__/api/postList.test.ts
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/src/api/postList.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/common/SearchBar/index.tsx
  frontend/src/components/post/PostList/constants.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/constants/post.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/hooks/usePostRequestInfo.ts
  frontend/src/mocks/wus/post.ts
  frontend/src/types/post.ts
Labels: FE, 🐾 개발

#197 H2 콘솔 원격 접속 허용
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/post/entity/PostBody.java
  backend/src/main/java/com/votogether/domain/post/entity/PostContentImages.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
Labels: BE, 🐛 버그

#198 multipartFile 관련 에러 디버깅
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/dto/request/PostCreateRequest.java
  backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionCreateRequest.java
  backend/src/main/resources/application.yml
Labels: BE, 🐛 버그

#200 이미지 파일 받기 위해 파라미터 네임 지정
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
Labels: BE, 🐛 버그

#202 디버깅을 위한 예외 추적 코드 추가
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
Labels: BE, 🐛 버그

#194 테스트 실패로 인해 빌드가 안되는 문제 수정
  frontend/__test__/hooks/useMoreComment.test.tsx
Labels: FE, 🐛 버그

#120 소셜 로그인(회원가입) 기능 구현
  frontend/.husky/pre-commit
  frontend/.husky/pre-push
  frontend/src/App.tsx
  frontend/src/api/post.ts
  frontend/src/api/wus/userInfo.ts
  frontend/src/assets/kakao_login_medium_wide.svg
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/hooks/context/auth.tsx
  frontend/src/hooks/query/user/useUserInfo.ts
  frontend/src/index.tsx
  frontend/src/pages/auth/Login.tsx
  frontend/src/pages/auth/Redirection.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/auth.ts
  frontend/src/types/user.ts
  frontend/src/utils/cookie/index.ts
  frontend/src/utils/fetch.ts
Labels: FE, 🐾 개발

#206 카카오 리다이렉트 URL 환경 변수 변경
  frontend/env.d.ts
  frontend/src/pages/auth/Login.tsx
Labels: FE, 🐛 버그, /(ㄒoㄒ)/~~

#207 이미지 파일 관련 에러 추적을 위한 코드 추가
  backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
Labels: BE, 🐛 버그

#209 이미지 파일 관련 에러 추적을 위한 코드 추가
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
Labels: BE, 🐛 버그

#211 이미지 파일 관련 에러 추적을 위한 코드 추가
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
Labels: BE, 🐛 버그

#212 이미지 파일 관련 에러 추적을 위한 코드 추가
  backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
Labels: BE, 🐛 버그

#214 에러 디버깅 관련 추적 코드 수정
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
Labels: BE, 🐛 버그

#213 글작성 폼 이미지 파일 잘못 전달되는 오류 수정 및 mock 카테고리 id가 전달되는 오류 수정_Feat/#210
  frontend/src/components/PostForm/ContentImageSection/index.tsx
  frontend/src/components/PostForm/ContentImageSection/style.ts
  frontend/src/components/PostForm/index.tsx
Labels: FE, 🐛 버그

#216 반환되는 날짜 데이터의 형식 수정
  backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
Labels: BE, 🐛 버그

#218 requestPart의 name 속성 생략
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
Labels: BE, 🛠 리팩터링

#219 카테고리, 게시글 목록 연동 및 리팩터링
  frontend/__test__/api/categoryList.test.ts
  frontend/__test__/api/postList.test.ts
  frontend/__test__/api/user.test.ts
  frontend/__test__/changeCategoryToOption.test.ts
  frontend/__test__/getDeadlineTime.test.ts
  frontend/__test__/hooks/query/useCategoryList.test.tsx
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/src/api/categoryList.ts
  frontend/src/api/comment.ts
  frontend/src/api/post.ts
  frontend/src/api/postList.ts
  frontend/src/api/userInfo.ts
  frontend/src/api/voteResult.ts
  frontend/src/components/PostForm/PostForm.stories.tsx
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/mockData.ts
  frontend/src/hooks/context/auth.tsx
  frontend/src/hooks/query/category/useCategoryFavoriteToggle.ts
  frontend/src/hooks/query/category/useCategoryList.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/hooks/query/user/useUserInfo.ts
  frontend/src/index.tsx
  frontend/src/mocks/categoryList.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/mockData/post.ts
  frontend/src/mocks/mockData/postList.ts
  frontend/src/mocks/post.ts
  frontend/src/mocks/postList.ts
  frontend/src/mocks/sua/post.ts
  frontend/src/mocks/userInfo.ts
  frontend/src/pages/MyInfo/index.tsx
  frontend/src/pages/post/EditPost/index.tsx
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/types/post.ts
  frontend/src/types/user.ts
  frontend/src/utils/post/changeCategoryToOption.ts
  frontend/src/utils/post/getDeadlineTime.ts
  frontend/src/utils/time.ts
Labels: FE, 🐾 개발

#222 핵심 기능 웹 접근성 개선하기_Feat/#203
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/WrittenVoteOption.stories.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/style.ts
  frontend/src/pages/VoteStatistics/OptionStatistics/index.tsx
Labels: FE, 🐾 개발

#225 게시글 타입 수정에 따른 반영이 되지 않아 게시글 컴포넌트에서 발생하는 오류 수정
  frontend/src/components/common/Post/index.tsx
  frontend/src/pages/MyInfo/index.tsx
Labels: FE, 🐾 개발

#226 작성자가 아니면 예외 처리하는 로직 삭제
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐛 버그

#227 게시글 생성, 투표지 선택 시 새로 고침해야 적용되는 버그
  frontend/__test__/hooks/query/useCreateVote.test.tsx
  frontend/__test__/hooks/query/useEditVote.test.tsx
  frontend/src/api/post.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/constants/post.ts
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/query/post/useCreatePost.ts
  frontend/src/hooks/query/post/useCreateVote.ts
  frontend/src/hooks/query/post/useEditVote.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/hooks/usePostRequestInfo.ts
  frontend/src/mocks/vote.ts
  frontend/src/utils/fetch.ts
Labels: FE, 🐾 개발, 🐛 버그, /(ㄒoㄒ)/~~

#234 없는 파일 이미지인 경우 빈값 반환
  backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostOptionDetailResponse.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
Labels: BE, 🐾 개발

#235 글 상세 페이지에서 이미지 url 수정 및 댓글 등록 fetch 함수 content type 수정
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/utils/fetch.ts
Labels: FE, 🐾 개발

#237 게시글 작성 시 content type 수정 및 댓글 수정 에러 해결
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/utils/fetch.ts
Labels: FE, 🐛 버그

#241 선호 카테고리 중복 추가 예외 수정
  backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
Labels: BE, 🐛 버그

#246 조기 마감 제한 제거
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐛 버그

#267 버그 제보 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/bug-report-버그-수정-템플릿-.md
Labels: 📄 문서

#264 초기 닉네임 생성 정책 변경
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/Nickname.java
  backend/src/test/java/com/votogether/domain/member/entity/NicknameTest.java
Labels: BE, 🛠 리팩터링

#134 내가 투표 한 글 조회 기능 구현
  backend/images/testImage1.PNG
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/entity/PostSortType.java
  backend/src/main/java/com/votogether/domain/post/repository/PostRepository.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
Labels: BE, 🐾 개발

#261 로그아웃 구현
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/hooks/context/auth.tsx
  frontend/src/pages/auth/Redirection.tsx
  frontend/src/types/user.ts
  frontend/src/utils/cookie/index.ts
Labels: FE, 🐾 개발

#286 (비회원) 게시글 상세 조회
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
Labels: BE, 🐾 개발

#294 utils의 fetch 함수 리팩터링, ErrorBoundary 구현, query를 이용한 에러핸들링
  frontend/src/api/example.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/hooks/query/post/useCreatePost.ts
  frontend/src/pages/ErrorBoundary.tsx
  frontend/src/pages/post/CreatePost/index.tsx
  frontend/src/utils/fetch.ts
Labels: FE, 🛠 리팩터링

#192 회원 닉네임 수정, 회원 탈퇴 react-query를 이용한 커스텀훅 구현
  frontend/__test__/api/user.test.ts
  frontend/__test__/hooks/query/useCancelMembership.test.tsx
  frontend/__test__/hooks/query/useModifyUser.test.tsx
  frontend/src/api/userInfo.ts
  frontend/src/hooks/query/user/useModifyUser.ts
  frontend/src/hooks/query/user/useWithdrawalMembership.ts
Labels: FE, 🐾 개발

#259 토스트/스낵바 컴포넌트 제작
  frontend/src/components/common/SnackBar/SnackBar.stories.tsx
  frontend/src/components/common/SnackBar/index.tsx
  frontend/src/components/common/SnackBar/style.ts
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/index.tsx
  frontend/src/components/common/Toast/style.ts
  frontend/src/components/common/ToastNSnackBarStyle.ts
  frontend/src/constants/animation.ts
  frontend/src/hooks/useToast.ts
Labels: FE, 🐾 개발

#288 게시글 옵션을 ContextApi를 이용해 전역으로 관리
  frontend/src/App.tsx
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostList/style.ts
  frontend/src/hooks/context/postOption.tsx
Labels: FE, 🐾 개발

#291 (비회원) 게시글 목록 조회
  backend/build.gradle
  backend/src/main/java/com/votogether/config/QuerydslConfig.java
  backend/src/main/java/com/votogether/domain/common/BaseEntity.java
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/dto/response/PostOptionResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/WriterResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/vote/VoteResponse.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCategoryRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/post/repository/PostRepository.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/global/persistence/OrderByNull.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/votogether/RepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
  backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
  backend/src/test/java/com/votogether/test/persister/Persister.java
  backend/src/test/java/com/votogether/test/persister/PostOptionTestPersister.java
  backend/src/test/java/com/votogether/test/persister/PostTestPersister.java
  backend/src/test/java/com/votogether/test/persister/VoteTestPersister.java
  backend/src/test/resources/application.yml
  frontend/src/hooks/query/comment/useEditComment.ts
  frontend/src/mocks/mockData/comment.ts
  frontend/src/types/comment.ts
Labels: BE, 🐾 개발

#262 투표글, 댓글, 닉네임 신고 기능 구현
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/NicknameNumberGenerator.java
  backend/src/main/java/com/votogether/domain/member/entity/NumberGenerator.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/comment/Comment.java
  backend/src/main/java/com/votogether/domain/post/repository/PostRepository.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportController.java
  backend/src/main/java/com/votogether/domain/report/dto/ReportRequest.java
  backend/src/main/java/com/votogether/domain/report/entity/Report.java
  backend/src/main/java/com/votogether/domain/report/entity/ReportType.java
  backend/src/main/java/com/votogether/domain/report/exception/ReportExceptionType.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportRepository.java
  backend/src/main/java/com/votogether/domain/report/service/ReportService.java
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportControllerTest.java
  backend/src/test/java/com/votogether/domain/report/repository/ReportRepositoryTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportServiceTest.java
  frontend/.storybook/preview.tsx
  frontend/__test__/api/user.test.ts
  frontend/__test__/hooks/query/useCancelMembership.test.tsx
  frontend/__test__/hooks/query/useModifyUser.test.tsx
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/src/App.tsx
  frontend/src/api/userInfo.ts
  frontend/src/components/common/SnackBar/SnackBar.stories.tsx
  frontend/src/components/common/SnackBar/index.tsx
  frontend/src/components/common/SnackBar/style.ts
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/index.tsx
  frontend/src/components/common/Toast/style.ts
  frontend/src/components/common/ToastNSnackBarStyle.ts
  frontend/src/components/post/EmptyPostList/EmptyPostList.stories.tsx
  frontend/src/components/post/EmptyPostList/index.tsx
  frontend/src/components/post/EmptyPostList/style.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostList/style.ts
  frontend/src/constants/animation.ts
  frontend/src/hooks/context/postOption.tsx
  frontend/src/hooks/query/comment/useEditComment.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/hooks/query/user/useModifyUser.ts
  frontend/src/hooks/query/user/useWithdrawalMembership.ts
  frontend/src/hooks/useToast.ts
  frontend/src/mocks/mockData/comment.ts
  frontend/src/mocks/postList.ts
  frontend/src/types/comment.ts
Labels: BE, 🐾 개발

#315 Revert "투표글, 댓글, 닉네임 신고 기능 구현 (#262)"
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/NicknameNumberGenerator.java
  backend/src/main/java/com/votogether/domain/member/entity/NumberGenerator.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/comment/Comment.java
  backend/src/main/java/com/votogether/domain/post/repository/PostRepository.java
  backend/src/main/java/com/votogether/domain/report/controller/ReportController.java
  backend/src/main/java/com/votogether/domain/report/dto/ReportRequest.java
  backend/src/main/java/com/votogether/domain/report/entity/Report.java
  backend/src/main/java/com/votogether/domain/report/entity/ReportType.java
  backend/src/main/java/com/votogether/domain/report/exception/ReportExceptionType.java
  backend/src/main/java/com/votogether/domain/report/repository/ReportRepository.java
  backend/src/main/java/com/votogether/domain/report/service/ReportService.java
  backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportControllerTest.java
  backend/src/test/java/com/votogether/domain/report/repository/ReportRepositoryTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportServiceTest.java
  frontend/.storybook/preview.tsx
  frontend/__test__/api/user.test.ts
  frontend/__test__/hooks/query/useCancelMembership.test.tsx
  frontend/__test__/hooks/query/useModifyUser.test.tsx
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/src/App.tsx
  frontend/src/api/userInfo.ts
  frontend/src/components/common/SnackBar/SnackBar.stories.tsx
  frontend/src/components/common/SnackBar/index.tsx
  frontend/src/components/common/SnackBar/style.ts
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/index.tsx
  frontend/src/components/common/Toast/style.ts
  frontend/src/components/common/ToastNSnackBarStyle.ts
  frontend/src/components/post/EmptyPostList/EmptyPostList.stories.tsx
  frontend/src/components/post/EmptyPostList/index.tsx
  frontend/src/components/post/EmptyPostList/style.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostList/style.ts
  frontend/src/constants/animation.ts
  frontend/src/hooks/context/postOption.tsx
  frontend/src/hooks/query/comment/useEditComment.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/hooks/query/user/useModifyUser.ts
  frontend/src/hooks/query/user/useWithdrawalMembership.ts
  frontend/src/hooks/useToast.ts
  frontend/src/mocks/mockData/comment.ts
  frontend/src/mocks/postList.ts
  frontend/src/types/comment.ts
Labels: BE, 🐾 개발

#296 게시글, 댓글, 닉네임 신고 API fetch 함수 구현 HTML5 해결
  frontend/public/index.html
  frontend/src/api/post.ts
  frontend/src/api/report.ts
  frontend/src/components/ReportModal/ReportModal.stories.tsx
  frontend/src/components/ReportModal/constants.ts
  frontend/src/components/ReportModal/index.tsx
  frontend/src/components/comment/CommentDeleteModal/CommentDeleteModal.stories.tsx
  frontend/src/components/comment/CommentDeleteModal/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/common/DeleteModal/DeleteModal.stories.tsx
  frontend/src/components/common/DeleteModal/index.tsx
  frontend/src/components/common/DeleteModal/style.ts
  frontend/src/components/common/PostMenu/PostMenu.stories.tsx
  frontend/src/components/common/PostMenu/index.tsx
  frontend/src/components/common/PostMenu/style.ts
  frontend/src/components/common/TwoButtonModal/index.tsx
  frontend/src/components/common/TwoButtonModal/style.ts
  frontend/src/components/report/CommentReportModal/CommentReportModal.stories.tsx
  frontend/src/components/report/CommentReportModal/constants.ts
  frontend/src/components/report/CommentReportModal/index.tsx
  frontend/src/components/report/CommentReportModal/types.ts
  frontend/src/components/report/UserReportModal/UserReportModal.stories.tsx
  frontend/src/components/report/UserReportModal/constants.ts
  frontend/src/components/report/UserReportModal/index.tsx
  frontend/src/components/report/UserReportModal/types.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/post.ts
  frontend/src/mocks/report.ts
  frontend/src/pages/post/PostDetail/BottomButtonPart/BottomButtonPart.stories.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/InnerHeaderPart.stories.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/style.ts
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/types/menu.ts
  frontend/src/types/report.ts
Labels: FE, 🐾 개발

#309 유저 정보, 카테고리 목록에서 캐싱, 스테일 타임을 1시간으로 수정
  frontend/src/hooks/query/category/useCategoryList.ts
  frontend/src/hooks/query/user/useUserInfo.ts
Labels: FE, 🐾 개발

#307 게시글 작성, 게시글 투표 시 유저의 정보가 변하도록 수정, 비회원 유저 정보 요청하지 않도록 수정
  frontend/__test__/api/user.test.ts
  frontend/src/api/userInfo.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/hooks/query/post/useCreatePost.ts
  frontend/src/hooks/query/post/useCreateVote.ts
  frontend/src/hooks/query/user/useUserInfo.ts
Labels: FE, 🐛 버그

#330 Member 스키마 수정에 따른 코드 변경
  backend/src/main/java/com/votogether/domain/auth/dto/KakaoMemberResponse.java
  backend/src/main/java/com/votogether/domain/member/dto/MemberInfoResponse.java
  backend/src/main/java/com/votogether/domain/member/entity/AgeRange.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/post/dto/response/vote/VoteOptionStatisticsResponse.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/domain/vote/dto/VoteStatus.java
  backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
  backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
  backend/src/test/java/com/votogether/domain/report/controller/ReportControllerTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportServiceTest.java
  backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
  backend/src/test/java/com/votogether/fixtures/MemberFixtures.java
  backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
  backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
Labels: BE, 🛠 리팩터링

#304 비회원 게시글 목록 조회 추가 기능 구현
  frontend/__test__/api/postList.test.ts
  frontend/__test__/api/vote.test.ts
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/src/api/comment.ts
  frontend/src/api/post.ts
  frontend/src/api/postList.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/constants/post.ts
  frontend/src/hooks/query/usePostList.tsx
  frontend/src/mocks/comment.ts
  frontend/src/mocks/mockData/postList.ts
  frontend/src/mocks/postList.ts
  frontend/src/mocks/vote.ts
  frontend/src/routes/router.tsx
  frontend/src/types/post.ts
Labels: FE, 🐾 개발, 🐛 버그

#318 현재 유저가 어떤 게시글 종류를 보고 있는지 정보를 반환하는 함수 구현 및 적용
  frontend/__test__/getPathFragment.test.ts
  frontend/__test__/getSelectedState.test.ts
  frontend/src/components/common/Dashboard/Dashboard.stories.tsx
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/utils/post/getSelectedState.ts
Labels: FE, 🐾 개발, 🐛 버그

#306 투표 상세보기에서 투표 변경사항이 즉시 적용되지 않음
  frontend/src/api/post.ts
  frontend/src/components/comment/CommentList/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/components/common/Select/style.ts
  frontend/src/hooks/context/auth.tsx
  frontend/src/hooks/query/post/useDeletePost.ts
  frontend/src/hooks/query/post/useEarlyClosePost.ts
  frontend/src/hooks/query/post/usePostDetail.ts
  frontend/src/pages/post/PostDetail/BottomButtonPart/BottomButtonPart.stories.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/InnerHeaderPart.stories.tsx
  frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/styles/theme.ts
  frontend/src/types/user.ts
  frontend/src/utils/time.ts
Labels: FE, 🐾 개발

#336 카카오 회원가입/로그인 응답 형식 수정
  backend/src/main/java/com/votogether/domain/auth/dto/LoginResponse.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
Labels: BE, 🛠 리팩터링

#337 내 정보 조회 응답 형식 수정
  backend/src/main/java/com/votogether/domain/member/dto/MemberInfoResponse.java
  backend/src/main/java/com/votogether/domain/member/entity/Gender.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
Labels: BE, 🛠 리팩터링

#312 Skeleton 애니메이션 변경, pr&issue 템플릿 변경, 글 수정 및 다중선택 컴포넌트 관련 버그 해결
  .github/ISSUE_TEMPLATE/feature-request-기능-개발-템플릿-.md
  .github/PULL_REQUEST_TEMPLATE.md
  frontend/src/components/PostForm/PostForm.stories.tsx
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/common/Layout/Layout.stories.tsx
  frontend/src/components/common/MultiSelect/index.tsx
  frontend/src/components/common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/common/Skeleton/index.tsx
  frontend/src/components/common/Skeleton/style.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/hooks/query/post/useEditPost.ts
  frontend/src/hooks/query/post/usePostDetail.ts
  frontend/src/pages/post/CreatePost/index.tsx
  frontend/src/pages/post/EditPost/index.tsx
  frontend/src/styles/theme.ts
  frontend/styled-components.d.ts
Labels: FE, 🛠 리팩터링, 🐛 버그

#320 사이트를 웹앱으로 실행되도록 하고, meta, favicon 설정
  frontend/public/icons/android-icon-144x144.png
  frontend/public/icons/android-icon-192x192.png
  frontend/public/icons/android-icon-36x36.png
  frontend/public/icons/android-icon-48x48.png
  frontend/public/icons/android-icon-512x512.png
  frontend/public/icons/android-icon-72x72.png
  frontend/public/icons/android-icon-96x96.png
  frontend/public/icons/apple-icon-114x114.png
  frontend/public/icons/apple-icon-120x120.png
  frontend/public/icons/apple-icon-144x144.png
  frontend/public/icons/apple-icon-152x152.png
  frontend/public/icons/apple-icon-180x180.png
  frontend/public/icons/apple-icon-57x57.png
  frontend/public/icons/apple-icon-60x60.png
  frontend/public/icons/apple-icon-72x72.png
  frontend/public/icons/apple-icon-76x76.png
  frontend/public/icons/apple-icon-precomposed.png
  frontend/public/icons/apple-icon.png
  frontend/public/icons/browserconfig.xml
  frontend/public/icons/favicon-16x16.png
  frontend/public/icons/favicon-32x32.png
  frontend/public/icons/favicon-96x96.png
  frontend/public/icons/favicon.ico
  frontend/public/icons/manifest.json
  frontend/public/icons/ms-icon-144x144.png
  frontend/public/icons/ms-icon-150x150.png
  frontend/public/icons/ms-icon-310x310.png
  frontend/public/icons/ms-icon-70x70.png
  frontend/public/icons/splash-screen-768x1004.png
  frontend/public/icons/thumbnail.png
  frontend/public/index.html
Labels: FE, 🐾 개발

#340 전체 게시글 조회시, 마감된 글은 투표 결과 전부 공개 기능 구현
  backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🛠 리팩터링

#335 [BUG] 게시물 상세페이지 반응성 적용 오류
  frontend/__test__/api/user.test.ts
  frontend/src/api/post.ts
  frontend/src/api/userInfo.ts
  frontend/src/components/PostForm/ContentImageSection/style.ts
  frontend/src/components/VoteStatistics/GraphStyle.ts
  frontend/src/components/VoteStatistics/TwoLineGraph/index.tsx
  frontend/src/components/VoteStatistics/TwoLineGraph/style.ts
  frontend/src/components/VoteStatistics/index.tsx
  frontend/src/components/VoteStatistics/style.ts
  frontend/src/components/VoteStatistics/type.ts
  frontend/src/components/common/Dashboard/Dashboard.stories.tsx
  frontend/src/components/common/Dashboard/UserProfile/UserProfile.stories.tsx
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/components/common/TagButton/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/mocks/mockData/user.ts
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/pages/post/PostDetail/style.ts
  frontend/src/types/user.ts
Labels: FE, 🐾 개발

#356 usePostDetail의 인수가 하나라서 발생하는 오류
  frontend/src/pages/post/EditPost/index.tsx
Labels: FE, 🐛 버그

#354 게시글 수정 기능 구현
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionUpdateRequest.java
  backend/src/main/java/com/votogether/domain/post/dto/request/PostUpdateRequest.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#350 성별, 출생년도 null 반환 가능하도록 수정
  backend/src/main/java/com/votogether/domain/member/dto/MemberInfoResponse.java
  backend/src/main/java/com/votogether/domain/member/entity/Gender.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
Labels: BE, 🛠 리팩터링

#357 게시글 삭제기능 구현 및 투표 20개 이상인 경우 예외 처리 기능 구현
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
  backend/src/main/java/com/votogether/domain/post/repository/PostContentImageRepository.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#339 성별, 나이 수정 기능 구현
  backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
  backend/src/main/java/com/votogether/domain/member/dto/MemberDetailRequest.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/main/java/com/votogether/domain/member/entity/MemberCategory.java
  backend/src/main/java/com/votogether/domain/member/entity/Nickname.java
  backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
  backend/src/main/java/com/votogether/domain/member/service/MemberService.java
  backend/src/main/java/com/votogether/domain/post/entity/PostCategory.java
  backend/src/main/java/com/votogether/domain/post/entity/PostContentImage.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
  backend/src/main/java/com/votogether/domain/report/entity/Report.java
  backend/src/main/java/com/votogether/domain/vote/entity/Vote.java
  backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#361 전체 게시글 목록 조회 시 카테고리도 함께 조회할 수 있도록 변경
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🛠 리팩터링

#295 내가 쓴 게시글 목록 조회 기능
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#314 (회원) 게시글 검색 기능
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#363 비회원 게시글 검색 기능
  backend/src/main/java/com/votogether/domain/post/controller/PostController.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
  backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
  backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
Labels: BE, 🐾 개발

#352 카테고리 목록 fetch하는 것을 컴포넌트 분리하여 Suspense와 에러 바운더리를 적용
  frontend/src/components/common/Dashboard/CategorySection/index.tsx
  frontend/src/components/common/Dashboard/CategorySection/style.ts
  frontend/src/components/common/Dashboard/Dashboard.stories.tsx
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/components/common/Dashboard/style.ts
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Layout/style.ts
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/hooks/query/category/useCategoryList.ts
  frontend/src/pages/ErrorBoundary.tsx
Labels: FE, 🛠 리팩터링, 🐛 버그

#353 api 오류 났을 때 토스트 띄우기
  frontend/src/components/PostForm/constants.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/CommentMenu/style.ts
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/comment/CommentList/constants.ts
  frontend/src/components/common/Dashboard/CategoryToggle/index.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/PostMenu/style.ts
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/hooks/query/comment/useCreateComment.ts
  frontend/src/hooks/query/comment/useEditComment.ts
  frontend/src/hooks/query/post/useCreateVote.ts
  frontend/src/hooks/query/post/useDeletePost.ts
  frontend/src/hooks/query/post/useEditVote.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/post/CreatePost/index.tsx
  frontend/src/pages/post/EditPost/index.tsx
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/utils/time.ts
Labels: FE, 🐾 개발

#364 게시글 전체 조회 시 이미지 경로 포함하도록 수정
  backend/src/main/java/com/votogether/domain/post/dto/response/PostOptionResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
  backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostOptionDetailResponse.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
Labels: BE, 🛠 리팩터링

#359 개인정보(성별/나이) 등록 페이지 구현, 회원탈퇴 및 닉네임 변경 API 함수에 UI와 연결
  frontend/__test__/api/user.test.ts
  frontend/src/api/userInfo.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/UserProfile.stories.tsx
  frontend/src/constants/comment.ts
  frontend/src/constants/path.ts
  frontend/src/constants/post.ts
  frontend/src/constants/user.ts
  frontend/src/hooks/query/user/useUserInfo.ts
  frontend/src/hooks/useText.ts
  frontend/src/mocks/mockData/user.ts
  frontend/src/mocks/userInfo.ts
  frontend/src/pages/MyInfo/index.tsx
  frontend/src/pages/user/RegisterPersonalInfo/RegisterPersonalInfo.stories.tsx
  frontend/src/pages/user/RegisterPersonalInfo/index.tsx
  frontend/src/pages/user/RegisterPersonalInfo/style.ts
  frontend/src/routes/router.tsx
  frontend/src/types/user.ts
Labels: FE, 🐾 개발

#362 게시글 작성 시 상세 게시글/카테고리 fetch하는 것을 컴포넌트 분리하여 Suspense와 에러 바운더리를 적용
  frontend/src/components/PostForm/CategoryWrapper/index.tsx
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/PostForm/style.ts
  frontend/src/components/common/NarrowTemplateHeader/index.tsx
  frontend/src/hooks/query/post/usePostDetail.ts
  frontend/src/pages/ErrorBoundaryWithNarrowHeader.tsx
  frontend/src/pages/ErrorBoundaryWithNarrowHeaderStyle.ts
  frontend/src/pages/MyInfo/index.tsx
  frontend/src/pages/post/CreatePostPage/index.tsx
  frontend/src/pages/post/EditPostPage/EditPost/index.tsx
  frontend/src/pages/post/EditPostPage/EditPostPage.stories.tsx
  frontend/src/pages/post/EditPostPage/index.tsx
  frontend/src/pages/post/EditPostPage/style.ts
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🐾 개발

#365 게시글 상세 조회 , 댓글 fetch하는 것을 컴포넌트 분리하여 Suspense와 에러 바운더리를 적용
  frontend/__test__/api/postList.test.ts
  frontend/__test__/hooks/query/usePostList.test.tsx
  frontend/src/components/comment/CommentList/CommentList.stories.tsx
  frontend/src/components/comment/CommentList/index.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/hooks/query/comment/useCommentList.ts
  frontend/src/mocks/mockData/post.ts
  frontend/src/mocks/mockData/postList.ts
  frontend/src/mocks/post.ts
  frontend/src/mocks/postList.ts
  frontend/src/pages/post/PostDetail/PostDetail/index.tsx
  frontend/src/pages/post/PostDetail/PostDetail/style.ts
  frontend/src/pages/post/PostDetail/PostDetailFallback/index.tsx
  frontend/src/pages/post/PostDetail/PostDetailFallback/style.ts
  frontend/src/pages/post/PostDetail/index.tsx
Labels: FE, 🛠 리팩터링, 🐾 개발

#375 로그인 시 응답하는 회원의 필수정보 필드 추가
  backend/src/main/java/com/votogether/domain/auth/dto/LoginResponse.java
  backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
  backend/src/main/java/com/votogether/domain/member/entity/Member.java
  backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
Labels: BE, 🛠 리팩터링

#378 MySQL 데이터소스 설정 추가
  backend/src/main/java/com/votogether/config/OpenAPIConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application.yml
Labels: BE, 🐾 개발

#380 MySQL 의존성 추가
  backend/build.gradle
Labels: BE, 🐾 개발

#373 빌드 시 public/icons에 있는 favicon, 아이콘 등을 빌드하도록 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
Labels: FE, 🐛 버그, 🐳 인프라

#382 게시글 수정을 할 때 마감시간이 설정되도록 구현
  frontend/__test__/calculateDeadlineTime.test.ts
  frontend/__test__/getSelectedTimeOption.test.ts
  frontend/src/components/PostForm/index.tsx
  frontend/src/utils/post/calculateDeadlineTime.ts
  frontend/src/utils/post/getSelectedTimeOption.ts
Labels: FE, 🛠 리팩터링, 🐾 개발, 🐛 버그

#383 상세 게시글에서 강력 새로고침 시 투표 인원수가 -1명으로 변하는 버그 수정
  frontend/src/hooks/query/post/useCreateVote.ts
  frontend/src/hooks/query/post/useEarlyClosePost.ts
  frontend/src/hooks/query/post/useEditVote.ts
  frontend/src/hooks/query/post/usePostDetail.ts
  frontend/src/pages/post/PostDetail/PostDetail/index.tsx
Labels: FE, 🐛 버그

#385 카테고리가 길 경우 스크롤이 되도록 변경, 리다이렉션 페이지에서 멤버 아이디를 설정하도록 수정
  frontend/src/components/common/Dashboard/CategorySection/style.ts
  frontend/src/pages/auth/Redirection.tsx
Labels: FE, 🛠 리팩터링

#390 로그 설정 파일 추가
  backend/build.gradle
  backend/src/main/resources/application.yml
  backend/src/main/resources/log4j2-dev.xml
  backend/src/main/resources/log4j2-local.xml
  backend/src/main/resources/log4j2-prod.xml
Labels: BE, 🐾 개발, 🐳 인프라

#386 [BUG] 현재 api me 가 무한으로 요청됨 외 1건
  frontend/src/App.tsx
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/components/common/ErrorMessage/index.tsx
  frontend/src/hooks/query/user/useModifyUser.ts
  frontend/src/hooks/query/user/useUserInfo.ts
  frontend/src/hooks/query/user/useWithdrawalMembership.ts
  frontend/src/pages/Error/index.tsx
  frontend/src/pages/Error/style.ts
  frontend/src/pages/ErrorBoundary.tsx
  frontend/src/pages/ErrorBoundaryForTopClass.tsx
  frontend/src/pages/ErrorBoundaryWithNarrowHeader.tsx
  frontend/src/pages/ErrorBoundaryWithNarrowHeaderStyle.ts
  frontend/src/pages/MyInfo/index.tsx
  frontend/src/pages/VoteStatisticsPage/OptionStatistics/OptionStatistics.stories.tsx
  frontend/src/pages/VoteStatisticsPage/OptionStatistics/index.tsx
  frontend/src/pages/VoteStatisticsPage/OptionStatistics/style.ts
  frontend/src/pages/VoteStatisticsPage/VoteStatistics.stories.tsx
  frontend/src/pages/VoteStatisticsPage/index.tsx
  frontend/src/pages/VoteStatisticsPage/style.ts
  frontend/src/pages/auth/Redirection.tsx
  frontend/src/pages/post/PostDetail/index.tsx
  frontend/src/pages/user/RegisterPersonalInfo/index.tsx
  frontend/src/routes/PrivateRoute.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/auth.ts
  frontend/src/utils/cookie/index.ts
Labels: FE, 🐾 개발, 🐛 버그

#389 [BUG] 모바일일때 검색 input 없음/ 로고버튼 이벤트 없음/ 마이페이지 이동 불가
  frontend/src/api/postList.ts
  frontend/src/components/common/Dashboard/UserProfile/index.tsx
  frontend/src/components/common/Dashboard/UserProfile/style.ts
  frontend/src/components/common/Dashboard/profileStyle.ts
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/NarrowMainHeader/NarrowMainHeader.stories.tsx
  frontend/src/components/common/NarrowMainHeader/index.tsx
  frontend/src/components/common/NarrowMainHeader/style.ts
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/pages/MyInfo/style.ts
Labels: FE, 🐾 개발, 🐛 버그

#395 비회원인데 신고가 가능한 버그, 비회원이 투표한 경우 토스트 띄우기
  frontend/src/components/common/Post/index.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/BottomButtonPart.stories.tsx
  frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
  frontend/src/pages/post/PostDetail/PostDetail/index.tsx
Labels: FE, 🐾 개발, 🐛 버그

#397 로그인했는데 마이페이지로 리다이렉트되는 버그, 회원탈퇴에 실패하는 버그 해결
  frontend/src/components/comment/CommentList/CommentLoginSection/index.tsx
  frontend/src/components/common/Dashboard/index.tsx
  frontend/src/hooks/context/auth.tsx
  frontend/src/hooks/query/user/useWithdrawalMembership.ts
  frontend/src/pages/MyInfo/DeleteMemberModal/index.tsx
  frontend/src/pages/MyInfo/DeleteMemberModal/style.ts
  frontend/src/pages/MyInfo/index.tsx
  frontend/src/pages/MyInfo/style.ts
Labels: FE, 🛠 리팩터링, 🐛 버그

#398 본문과 내용에 사진을 추가할 때 안될 때가 있다
  frontend/src/api/post.ts
  frontend/src/api/report.ts
  frontend/src/components/PostForm/ContentImageSection/index.tsx
  frontend/src/hooks/useContentImage.ts
Labels: FE, 🐛 버그

#401 회원이 마감 완료된 게시글에 투표할 때 failed to Fetch가 나타나요, 마감된 게시글 투표 통계 보이도록 수정
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/WrittenVoteOption.stories.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOptionList.stories.tsx
  frontend/src/components/optionList/WrittenVoteOptionList/index.tsx
  frontend/src/pages/VoteStatisticsPage/OptionStatistics/index.tsx
Labels: FE, 🐾 개발, 🐛 버그

#404 모바일에서 검색창 눌러서 검색이 가능하도록 수정
  frontend/src/components/common/NarrowMainHeader/index.tsx
  frontend/src/components/common/SearchBar/index.tsx
  frontend/src/components/post/PostListPage/style.ts
Labels: FE, 🐛 버그

#406 로그인 페이지 UI 구현 및 적용 (피그마 시안)
  frontend/src/assets.d.ts
  frontend/src/assets/stroke-logo.svg
  frontend/src/assets/votogether_home.png
  frontend/src/assets/votogether_write.png
  frontend/src/pages/auth/Login.tsx
  frontend/src/pages/auth/Login/Login.stories.tsx
  frontend/src/pages/auth/Login/MobileLogin/MobileLogin.stories.tsx
  frontend/src/pages/auth/Login/MobileLogin/index.tsx
  frontend/src/pages/auth/Login/MobileLogin/style.ts
  frontend/src/pages/auth/Login/ServiceIntroductionSection/StartUsingOurService.stories.tsx
  frontend/src/pages/auth/Login/ServiceIntroductionSection/index.tsx
  frontend/src/pages/auth/Login/ServiceIntroductionSection/style.ts
  frontend/src/pages/auth/Login/index.tsx
  frontend/src/pages/auth/Login/style.ts
  frontend/src/svg.d.ts
  frontend/webpack.common.js
Labels: FE, 🐾 개발

#434 게시글 수정 디버깅
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostBody.java
  backend/src/main/java/com/votogether/domain/post/entity/PostCategories.java
  backend/src/main/java/com/votogether/domain/post/entity/PostContentImage.java
  backend/src/main/java/com/votogether/domain/post/entity/PostContentImages.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOptions.java
  backend/src/test/java/com/votogether/domain/post/entity/PostOptionsTest.java
  backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
Labels: BE, 🐾 개발

#441 게시글과 댓글이 신고 5번 이상이어도 보이는 버그 픽스
  backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
  backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
  backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
  backend/src/test/java/com/votogether/domain/post/repository/CommentRepositoryTest.java
  backend/src/test/java/com/votogether/domain/report/service/ReportServiceTest.java
Labels: BE, 🐛 버그

#445 PostOption이 수정할 때 전부 지워지도록 개선
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOptions.java
Labels: BE, 🐛 버그

#440 본문글 개행 적용, 모달 외부 누르면 모달 닫히기 적용, 즐겨찾기 아이콘 수정, API 통신 실패 시 Toast에 띄울 메시지 가공
  frontend/src/assets/star-filled.svg
  frontend/src/assets/star-lined.svg
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/components/common/Dashboard/CategoryToggle/index.tsx
  frontend/src/components/common/Dashboard/CategoryToggle/style.ts
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/common/Post/style.ts
  frontend/src/components/common/TwoButtonModal/index.tsx
  frontend/src/pages/post/CreatePostPage/index.tsx
  frontend/src/pages/post/EditPostPage/EditPost/index.tsx
  frontend/src/pages/post/PostDetail/PostDetail/index.tsx
Labels: FE, 🐛 버그

#435 글을 작성하면 리스트 정렬기준이 "최신순"으로 바꾸기, 라우팅 시 스크롤 최상단으로 이동하기
  frontend/src/components/comment/CommentList/index.tsx
  frontend/src/components/common/ScrollToTop/index.tsx
  frontend/src/components/post/PostListPage/index.tsx
  frontend/src/pages/post/CreatePostPage/index.tsx
  frontend/src/pages/post/EditPostPage/EditPost/index.tsx
  frontend/src/routes/router.tsx
  frontend/src/utils/scrollToTop.ts
Labels: FE, 🐛 버그

#449 게시글 수정 시, PostOption 테이블 유니크 값 충돌 문제 해결
  backend/src/main/java/com/votogether/domain/post/entity/Post.java
  backend/src/main/java/com/votogether/domain/post/entity/PostOptions.java
  backend/src/main/java/com/votogether/domain/post/service/PostService.java
Labels: BE, 🐛 버그

#454 NarrowMainHeader, Select, Searchbar, Skeleton 컴포넌트 웹접근성 개선 / 닉네임 변경 및 신고 API 실패 시 Toast 띄우기
  frontend/src/components/comment/CommentList/CommentItem/index.tsx
  frontend/src/components/comment/CommentList/CommentItem/style.ts
  frontend/src/components/common/LogoButton/index.tsx
  frontend/src/components/common/NarrowMainHeader/index.tsx
  frontend/src/components/common/NarrowMainHeader/style.ts
  frontend/src/components/common/SearchBar/index.tsx
  frontend/src/components/common/SearchBar/style.ts
  frontend/src/components/common/Select/index.tsx
  frontend/src/components/common/Select/style.ts
  frontend/src/components/common/Skeleton/index.tsx
  frontend/src/components/post/PostList/index.tsx
  frontend/src/hooks/query/user/useModifyUser.ts
  frontend/src/pages/MyInfo/index.tsx
  frontend/src/pages/post/PostDetail/PostDetail/index.tsx
  frontend/src/styles/globalStyle.ts
Labels: FE, 🛠 리팩터링, 🐛 버그

#450 Drawer, ErrorMessage, HeaderTextButton, IconButton, Layout 컴포넌트 웹접근성 높이기
  frontend/src/components/PostForm/index.tsx
  frontend/src/components/common/Drawer/index.tsx
  frontend/src/components/common/Drawer/style.ts
  frontend/src/components/common/IconButton/IconButton.stories.tsx
  frontend/src/components/common/LoadingSpinner/index.tsx
  frontend/src/components/common/LogoButton/index.tsx
  frontend/src/components/common/MultiSelect/index.tsx
  frontend/src/components/common/MultiSelect/style.ts
  frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
  frontend/src/constants/post.ts
  frontend/src/utils/post/convertImageUrlToServerUrl.ts
Labels: FE, 🐾 개발, 🐛 버그

#462 README.md 작성
  frontend/README.md
Labels: FE, 📄 문서

#465 [BUG] 상세 게시글에서 이미지 수정 후 새로고침해야 바뀐 이미지로 보여요
  frontend/src/hooks/query/post/useEditPost.ts
Labels: FE, 🐛 버그

#466 토스트가 계속해서 뜨는 문제 수정
  frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
  frontend/src/pages/MyInfo/index.tsx
Labels: FE, 🐛 버그

#469 [BUG] 모바일/데스크탑에서 사진을 2번씩 눌러야 이미지 첨부가 돼요
  frontend/src/components/PostForm/ContentImageSection/index.tsx
  frontend/src/components/common/Post/index.tsx
  frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/index.tsx
  frontend/src/pages/Error/index.tsx
  frontend/src/pages/MyInfo/index.tsx
Labels: FE, 🐛 버그

#452 인터넷 익스플로어로 접속 시 브라우저를 업데이트 해달라는 기능 구현
  frontend/src/components/PostForm/constants.ts
  frontend/src/components/post/PostList/index.tsx
  frontend/src/constants/policyMessage.ts
  frontend/src/constants/post.ts
  frontend/src/hooks/useContentImage.ts
  frontend/src/hooks/useWritingOption.tsx
  frontend/src/index.tsx
Labels: FE, 🐾 개발

#472 [BUG] README 프론트엔드 경로에 되어 있는 것 수정
  README.md
  frontend/README.md
Labels: FE, 📄 문서
